<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>15 Social Influence: Coevolution of Networks and Behaviors | Network Analysis: Integrating Social Network Theory, Method, and Application with R</title>
  <meta name="description" content="This is the website for the R tutorials associated with Network Analysis Integrating Social Network Theory, Method, and Application with R" />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="15 Social Influence: Coevolution of Networks and Behaviors | Network Analysis: Integrating Social Network Theory, Method, and Application with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is the website for the R tutorials associated with Network Analysis Integrating Social Network Theory, Method, and Application with R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="15 Social Influence: Coevolution of Networks and Behaviors | Network Analysis: Integrating Social Network Theory, Method, and Application with R" />
  
  <meta name="twitter:description" content="This is the website for the R tutorials associated with Network Analysis Integrating Social Network Theory, Method, and Application with R" />
  

<meta name="author" content="Craig Rawlings, Jeffrey A. Smith, James Moody, and Daniel McFarland" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ch14-Network-Diffusion-Social-Processes-R.html"/>
<link rel="next" href="how-to-cite.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="libs/d3-4.5.0/d3.min.js"></script>
<script src="libs/forceNetwork-binding-0.4/forceNetwork.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://inarwhal.github.io/NetworkAnalysisR-book/">
Network Analysis with R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#how-to-read-the-book"><i class="fa fa-check"></i><b>1.1</b> How to Read the Book</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#citations-and-use"><i class="fa fa-check"></i><b>1.2</b> Citations and Use</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#updates-and-feedback"><i class="fa fa-check"></i><b>1.3</b> Updates and Feedback</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#acknowledgments"><i class="fa fa-check"></i><b>1.4</b> Acknowledgments</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#author-informtion"><i class="fa fa-check"></i><b>1.5</b> Author Informtion</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#session-information"><i class="fa fa-check"></i><b>1.6</b> Session Information</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ch2-intro-R.html"><a href="ch2-intro-R.html"><i class="fa fa-check"></i><b>2</b> Basic Introduction to R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="ch2-intro-R.html"><a href="ch2-intro-R.html#preliminaries"><i class="fa fa-check"></i><b>2.1</b> Preliminaries</a></li>
<li class="chapter" data-level="2.2" data-path="ch2-intro-R.html"><a href="ch2-intro-R.html#packages"><i class="fa fa-check"></i><b>2.2</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ch3-Network-Data-R.html"><a href="ch3-Network-Data-R.html"><i class="fa fa-check"></i><b>3</b> Network Data</a></li>
<li class="chapter" data-level="" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html"><i class="fa fa-check"></i>3, Part 1. Cross-Sectional Network Data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html#reading-data-into-r"><i class="fa fa-check"></i><b>3.1</b> Reading Data into R</a></li>
<li class="chapter" data-level="3.2" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html#networks-in-igraph"><i class="fa fa-check"></i><b>3.2</b> Networks in igraph</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html#using-a-matrix-to-construct-the-network"><i class="fa fa-check"></i><b>3.2.1</b> Using a Matrix to Construct the Network</a></li>
<li class="chapter" data-level="3.2.2" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html#using-an-edgelist-to-construct-the-network"><i class="fa fa-check"></i><b>3.2.2</b> Using an Edgelist to Construct the Network</a></li>
<li class="chapter" data-level="3.2.3" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html#extracting-information-from-igraph-objects"><i class="fa fa-check"></i><b>3.2.3</b> Extracting Information from igraph Objects</a></li>
<li class="chapter" data-level="3.2.4" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html#using-an-adjacency-list-to-construct-the-network"><i class="fa fa-check"></i><b>3.2.4</b> Using an Adjacency List to Construct the Network</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html#using-the-network-package"><i class="fa fa-check"></i><b>3.3</b> Using the network Package</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html#using-a-matrix-to-construct-the-network-1"><i class="fa fa-check"></i><b>3.3.1</b> Using a Matrix to Construct the Network</a></li>
<li class="chapter" data-level="3.3.2" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html#using-an-edgelist-to-construct-the-network-1"><i class="fa fa-check"></i><b>3.3.2</b> Using an Edgelist to Construct the Network</a></li>
<li class="chapter" data-level="3.3.3" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html#putting-edge-attributes-onto-the-network"><i class="fa fa-check"></i><b>3.3.3</b> Putting Edge Attributes onto the Network</a></li>
<li class="chapter" data-level="3.3.4" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html#moving-between-igraph-and-network-objects"><i class="fa fa-check"></i><b>3.3.4</b> Moving between igraph and network Objects</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html#some-key-network-measures"><i class="fa fa-check"></i><b>3.4</b> Some Key Network Measures</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html#degree"><i class="fa fa-check"></i><b>3.4.1</b> Degree</a></li>
<li class="chapter" data-level="3.4.2" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html#density"><i class="fa fa-check"></i><b>3.4.2</b> Density</a></li>
<li class="chapter" data-level="3.4.3" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html#walks"><i class="fa fa-check"></i><b>3.4.3</b> Walks</a></li>
<li class="chapter" data-level="3.4.4" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html#paths-distance-and-closeness"><i class="fa fa-check"></i><b>3.4.4</b> Paths, Distance, and Closeness</a></li>
<li class="chapter" data-level="3.4.5" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html#reachability"><i class="fa fa-check"></i><b>3.4.5</b> Reachability</a></li>
<li class="chapter" data-level="3.4.6" data-path="ch3-Cross-Sectional-Network-Data-R.html"><a href="ch3-Cross-Sectional-Network-Data-R.html#diameter"><i class="fa fa-check"></i><b>3.4.6</b> Diameter</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch3-Dynamic-Network-Data-R.html"><a href="ch3-Dynamic-Network-Data-R.html"><i class="fa fa-check"></i>3, Part 2. Dynamic Network Data</a>
<ul>
<li class="chapter" data-level="3.5" data-path="ch3-Dynamic-Network-Data-R.html"><a href="ch3-Dynamic-Network-Data-R.html#discrete-longitudinal-networks"><i class="fa fa-check"></i><b>3.5</b> Discrete Longitudinal Networks</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="ch3-Dynamic-Network-Data-R.html"><a href="ch3-Dynamic-Network-Data-R.html#getting-the-data-ready"><i class="fa fa-check"></i><b>3.5.1</b> Getting the Data Ready</a></li>
<li class="chapter" data-level="3.5.2" data-path="ch3-Dynamic-Network-Data-R.html"><a href="ch3-Dynamic-Network-Data-R.html#constructing-networkdynamic-objects"><i class="fa fa-check"></i><b>3.5.2</b> Constructing networkDynamic Objects</a></li>
<li class="chapter" data-level="3.5.3" data-path="ch3-Dynamic-Network-Data-R.html"><a href="ch3-Dynamic-Network-Data-R.html#summary-statistics"><i class="fa fa-check"></i><b>3.5.3</b> Summary Statistics</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="ch3-Dynamic-Network-Data-R.html"><a href="ch3-Dynamic-Network-Data-R.html#continuous-time-networks"><i class="fa fa-check"></i><b>3.6</b> Continuous-Time Networks</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="ch3-Dynamic-Network-Data-R.html"><a href="ch3-Dynamic-Network-Data-R.html#getting-the-data-ready-1"><i class="fa fa-check"></i><b>3.6.1</b> Getting the Data Ready</a></li>
<li class="chapter" data-level="3.6.2" data-path="ch3-Dynamic-Network-Data-R.html"><a href="ch3-Dynamic-Network-Data-R.html#constructing-networkdynamic-objects-1"><i class="fa fa-check"></i><b>3.6.2</b> Constructing networkDynamic Objects</a></li>
<li class="chapter" data-level="3.6.3" data-path="ch3-Dynamic-Network-Data-R.html"><a href="ch3-Dynamic-Network-Data-R.html#summary-statistics-1"><i class="fa fa-check"></i><b>3.6.3</b> Summary Statistics</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ch4-Missing-Network-Data-R.html"><a href="ch4-Missing-Network-Data-R.html"><i class="fa fa-check"></i><b>4</b> Missing Network Data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="ch4-Missing-Network-Data-R.html"><a href="ch4-Missing-Network-Data-R.html#missing-data"><i class="fa fa-check"></i><b>4.1</b> Missing Data</a></li>
<li class="chapter" data-level="4.2" data-path="ch4-Missing-Network-Data-R.html"><a href="ch4-Missing-Network-Data-R.html#listwise-deletion"><i class="fa fa-check"></i><b>4.2</b> Listwise Deletion</a></li>
<li class="chapter" data-level="4.3" data-path="ch4-Missing-Network-Data-R.html"><a href="ch4-Missing-Network-Data-R.html#gauging-the-level-of-bias"><i class="fa fa-check"></i><b>4.3</b> Gauging the Level of Bias</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="ch4-Missing-Network-Data-R.html"><a href="ch4-Missing-Network-Data-R.html#gauging-bias-using-past-results"><i class="fa fa-check"></i><b>4.3.1</b> Gauging Bias Using Past Results</a></li>
<li class="chapter" data-level="4.3.2" data-path="ch4-Missing-Network-Data-R.html"><a href="ch4-Missing-Network-Data-R.html#gauging-bias-using-predictive-models"><i class="fa fa-check"></i><b>4.3.2</b> Gauging Bias Using Predictive Models</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="ch4-Missing-Network-Data-R.html"><a href="ch4-Missing-Network-Data-R.html#simple-imputation-options"><i class="fa fa-check"></i><b>4.4</b> Simple Imputation Options</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="ch4-Missing-Network-Data-R.html"><a href="ch4-Missing-Network-Data-R.html#simple-imputation-with-asymmetric-option"><i class="fa fa-check"></i><b>4.4.1</b> Simple Imputation with Asymmetric Option</a></li>
<li class="chapter" data-level="4.4.2" data-path="ch4-Missing-Network-Data-R.html"><a href="ch4-Missing-Network-Data-R.html#simple-imputation-with-symmetric-option"><i class="fa fa-check"></i><b>4.4.2</b> Simple Imputation with Symmetric Option</a></li>
<li class="chapter" data-level="4.4.3" data-path="ch4-Missing-Network-Data-R.html"><a href="ch4-Missing-Network-Data-R.html#simple-imputation-with-probabilistic-option"><i class="fa fa-check"></i><b>4.4.3</b> Simple Imputation with Probabilistic Option</a></li>
<li class="chapter" data-level="4.4.4" data-path="ch4-Missing-Network-Data-R.html"><a href="ch4-Missing-Network-Data-R.html#comparing-estimates"><i class="fa fa-check"></i><b>4.4.4</b> Comparing Estimates</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ch5-Network-Visualization-R.html"><a href="ch5-Network-Visualization-R.html"><i class="fa fa-check"></i><b>5</b> Network Visualization</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ch5-Network-Visualization-R.html"><a href="ch5-Network-Visualization-R.html#setting-up-the-session"><i class="fa fa-check"></i><b>5.1</b> Setting up the Session</a></li>
<li class="chapter" data-level="5.2" data-path="ch5-Network-Visualization-R.html"><a href="ch5-Network-Visualization-R.html#network-plots-using-igraph"><i class="fa fa-check"></i><b>5.2</b> Network Plots using igraph</a></li>
<li class="chapter" data-level="5.3" data-path="ch5-Network-Visualization-R.html"><a href="ch5-Network-Visualization-R.html#network-plots-based-on-ggplot"><i class="fa fa-check"></i><b>5.3</b> Network Plots based on ggplot</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="ch5-Network-Visualization-R.html"><a href="ch5-Network-Visualization-R.html#ggally-package"><i class="fa fa-check"></i><b>5.3.1</b> GGally package</a></li>
<li class="chapter" data-level="5.3.2" data-path="ch5-Network-Visualization-R.html"><a href="ch5-Network-Visualization-R.html#ggnetwork-package"><i class="fa fa-check"></i><b>5.3.2</b> ggnetwork package</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="ch5-Network-Visualization-R.html"><a href="ch5-Network-Visualization-R.html#contour-plots"><i class="fa fa-check"></i><b>5.4</b> Contour Plots</a></li>
<li class="chapter" data-level="5.5" data-path="ch5-Network-Visualization-R.html"><a href="ch5-Network-Visualization-R.html#interactive-plots"><i class="fa fa-check"></i><b>5.5</b> Interactive Plots</a></li>
<li class="chapter" data-level="5.6" data-path="ch5-Network-Visualization-R.html"><a href="ch5-Network-Visualization-R.html#dynamic-network-visualizations"><i class="fa fa-check"></i><b>5.6</b> Dynamic Network Visualizations</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="ch5-Network-Visualization-R.html"><a href="ch5-Network-Visualization-R.html#getting-the-data-ready-2"><i class="fa fa-check"></i><b>5.6.1</b> Getting the Data Ready</a></li>
<li class="chapter" data-level="5.6.2" data-path="ch5-Network-Visualization-R.html"><a href="ch5-Network-Visualization-R.html#time-flattened-visualizations"><i class="fa fa-check"></i><b>5.6.2</b> Time Flattened Visualizations</a></li>
<li class="chapter" data-level="5.6.3" data-path="ch5-Network-Visualization-R.html"><a href="ch5-Network-Visualization-R.html#dynamic-network-movies"><i class="fa fa-check"></i><b>5.6.3</b> Dynamic Network Movies</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ch6-Ego-Network-Data-R.html"><a href="ch6-Ego-Network-Data-R.html"><i class="fa fa-check"></i><b>6</b> Ego Network Data</a>
<ul>
<li class="chapter" data-level="6.1" data-path="ch6-Ego-Network-Data-R.html"><a href="ch6-Ego-Network-Data-R.html#working-with-ego-network-data"><i class="fa fa-check"></i><b>6.1</b> Working with Ego Network Data</a></li>
<li class="chapter" data-level="6.2" data-path="ch6-Ego-Network-Data-R.html"><a href="ch6-Ego-Network-Data-R.html#plotting-networks"><i class="fa fa-check"></i><b>6.2</b> Plotting Networks</a></li>
<li class="chapter" data-level="6.3" data-path="ch6-Ego-Network-Data-R.html"><a href="ch6-Ego-Network-Data-R.html#homophily-ego-alter-attributes"><i class="fa fa-check"></i><b>6.3</b> Homophily: Ego-Alter Attributes</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="ch6-Ego-Network-Data-R.html"><a href="ch6-Ego-Network-Data-R.html#proportion-of-alters-matching-ego"><i class="fa fa-check"></i><b>6.3.1</b> Proportion of Alters Matching Ego</a></li>
<li class="chapter" data-level="6.3.2" data-path="ch6-Ego-Network-Data-R.html"><a href="ch6-Ego-Network-Data-R.html#analyzing-homophily-at-the-dyadic-level-ego-alter-pairs"><i class="fa fa-check"></i><b>6.3.2</b> Analyzing Homophily at the Dyadic Level: Ego-Alter Pairs</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="ch6-Ego-Network-Data-R.html"><a href="ch6-Ego-Network-Data-R.html#homophily-alter-attributes"><i class="fa fa-check"></i><b>6.4</b> Homophily: Alter Attributes</a></li>
<li class="chapter" data-level="6.5" data-path="ch6-Ego-Network-Data-R.html"><a href="ch6-Ego-Network-Data-R.html#ego-networks-as-predictors"><i class="fa fa-check"></i><b>6.5</b> Ego Networks as Predictors</a></li>
<li class="chapter" data-level="6.6" data-path="ch6-Ego-Network-Data-R.html"><a href="ch6-Ego-Network-Data-R.html#working-with-one-input-file"><i class="fa fa-check"></i><b>6.6</b> Working with One Input File</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ch7-Dyads-Triads-R.html"><a href="ch7-Dyads-Triads-R.html"><i class="fa fa-check"></i><b>7</b> Dyads and Triads</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ch7-Dyads-Triads-R.html"><a href="ch7-Dyads-Triads-R.html#setting-up-the-session-1"><i class="fa fa-check"></i><b>7.1</b> Setting up the Session</a></li>
<li class="chapter" data-level="7.2" data-path="ch7-Dyads-Triads-R.html"><a href="ch7-Dyads-Triads-R.html#dyadic-processes"><i class="fa fa-check"></i><b>7.2</b> Dyadic Processes</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="ch7-Dyads-Triads-R.html"><a href="ch7-Dyads-Triads-R.html#dyad-census-and-reciprocity"><i class="fa fa-check"></i><b>7.2.1</b> Dyad Census and Reciprocity</a></li>
<li class="chapter" data-level="7.2.2" data-path="ch7-Dyads-Triads-R.html"><a href="ch7-Dyads-Triads-R.html#conditional-uniform-graph-tests"><i class="fa fa-check"></i><b>7.2.2</b> Conditional Uniform Graph Tests</a></li>
<li class="chapter" data-level="7.2.3" data-path="ch7-Dyads-Triads-R.html"><a href="ch7-Dyads-Triads-R.html#dyad-census-by-attributes-of-nodes"><i class="fa fa-check"></i><b>7.2.3</b> Dyad Census by Attributes of Nodes</a></li>
<li class="chapter" data-level="7.2.4" data-path="ch7-Dyads-Triads-R.html"><a href="ch7-Dyads-Triads-R.html#advice-and-friendship-together"><i class="fa fa-check"></i><b>7.2.4</b> Advice and Friendship Together</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="ch7-Dyads-Triads-R.html"><a href="ch7-Dyads-Triads-R.html#triadic-processes"><i class="fa fa-check"></i><b>7.3</b> Triadic Processes</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="ch7-Dyads-Triads-R.html"><a href="ch7-Dyads-Triads-R.html#triad-census"><i class="fa fa-check"></i><b>7.3.1</b> Triad Census</a></li>
<li class="chapter" data-level="7.3.2" data-path="ch7-Dyads-Triads-R.html"><a href="ch7-Dyads-Triads-R.html#transitivity"><i class="fa fa-check"></i><b>7.3.2</b> Transitivity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ch8-Network-Cohesion-Communities-R.html"><a href="ch8-Network-Cohesion-Communities-R.html"><i class="fa fa-check"></i><b>8</b> Network Cohesion and Communities</a>
<ul>
<li class="chapter" data-level="8.1" data-path="ch8-Network-Cohesion-Communities-R.html"><a href="ch8-Network-Cohesion-Communities-R.html#first-example-network"><i class="fa fa-check"></i><b>8.1</b> First Example Network</a></li>
<li class="chapter" data-level="8.2" data-path="ch8-Network-Cohesion-Communities-R.html"><a href="ch8-Network-Cohesion-Communities-R.html#cohesion"><i class="fa fa-check"></i><b>8.2</b> Cohesion</a></li>
<li class="chapter" data-level="8.3" data-path="ch8-Network-Cohesion-Communities-R.html"><a href="ch8-Network-Cohesion-Communities-R.html#community-or-group-detection"><i class="fa fa-check"></i><b>8.3</b> Community (or Group) Detection</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="ch8-Network-Cohesion-Communities-R.html"><a href="ch8-Network-Cohesion-Communities-R.html#walktrap"><i class="fa fa-check"></i><b>8.3.1</b> Walktrap</a></li>
<li class="chapter" data-level="8.3.2" data-path="ch8-Network-Cohesion-Communities-R.html"><a href="ch8-Network-Cohesion-Communities-R.html#edge-betweenness"><i class="fa fa-check"></i><b>8.3.2</b> Edge Betweenness</a></li>
<li class="chapter" data-level="8.3.3" data-path="ch8-Network-Cohesion-Communities-R.html"><a href="ch8-Network-Cohesion-Communities-R.html#scree-plots"><i class="fa fa-check"></i><b>8.3.3</b> Scree Plots</a></li>
<li class="chapter" data-level="8.3.4" data-path="ch8-Network-Cohesion-Communities-R.html"><a href="ch8-Network-Cohesion-Communities-R.html#multi-level-clustering"><i class="fa fa-check"></i><b>8.3.4</b> Multi-level Clustering</a></li>
<li class="chapter" data-level="8.3.5" data-path="ch8-Network-Cohesion-Communities-R.html"><a href="ch8-Network-Cohesion-Communities-R.html#cohesive-blocking"><i class="fa fa-check"></i><b>8.3.5</b> Cohesive Blocking</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="ch8-Network-Cohesion-Communities-R.html"><a href="ch8-Network-Cohesion-Communities-R.html#demographic-characteristics"><i class="fa fa-check"></i><b>8.4</b> Demographic Characteristics</a></li>
<li class="chapter" data-level="8.5" data-path="ch8-Network-Cohesion-Communities-R.html"><a href="ch8-Network-Cohesion-Communities-R.html#community-overlap"><i class="fa fa-check"></i><b>8.5</b> Community Overlap</a></li>
<li class="chapter" data-level="8.6" data-path="ch8-Network-Cohesion-Communities-R.html"><a href="ch8-Network-Cohesion-Communities-R.html#big-data-example"><i class="fa fa-check"></i><b>8.6</b> Big Data Example</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="ch8-Network-Cohesion-Communities-R.html"><a href="ch8-Network-Cohesion-Communities-R.html#multi-level-clustering-1"><i class="fa fa-check"></i><b>8.6.1</b> Multi-level Clustering</a></li>
<li class="chapter" data-level="8.6.2" data-path="ch8-Network-Cohesion-Communities-R.html"><a href="ch8-Network-Cohesion-Communities-R.html#looking-at-the-community-structure-within-the-initial-communities"><i class="fa fa-check"></i><b>8.6.2</b> Looking at the Community Structure within the Initial Communities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ch9-Network-Centrality-Hierarchy-R.html"><a href="ch9-Network-Centrality-Hierarchy-R.html"><i class="fa fa-check"></i><b>9</b> Network Centrality and Hierarchy</a>
<ul>
<li class="chapter" data-level="9.1" data-path="ch9-Network-Centrality-Hierarchy-R.html"><a href="ch9-Network-Centrality-Hierarchy-R.html#setting-up-the-session-2"><i class="fa fa-check"></i><b>9.1</b> Setting up the Session</a></li>
<li class="chapter" data-level="9.2" data-path="ch9-Network-Centrality-Hierarchy-R.html"><a href="ch9-Network-Centrality-Hierarchy-R.html#centrality"><i class="fa fa-check"></i><b>9.2</b> Centrality</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="ch9-Network-Centrality-Hierarchy-R.html"><a href="ch9-Network-Centrality-Hierarchy-R.html#centrality-measures-for-social-interactions"><i class="fa fa-check"></i><b>9.2.1</b> Centrality Measures for Social Interactions</a></li>
<li class="chapter" data-level="9.2.2" data-path="ch9-Network-Centrality-Hierarchy-R.html"><a href="ch9-Network-Centrality-Hierarchy-R.html#correlations-between-centrality-measures"><i class="fa fa-check"></i><b>9.2.2</b> Correlations between Centrality Measures</a></li>
<li class="chapter" data-level="9.2.3" data-path="ch9-Network-Centrality-Hierarchy-R.html"><a href="ch9-Network-Centrality-Hierarchy-R.html#centrality-for-task-interactions"><i class="fa fa-check"></i><b>9.2.3</b> Centrality for Task Interactions</a></li>
<li class="chapter" data-level="9.2.4" data-path="ch9-Network-Centrality-Hierarchy-R.html"><a href="ch9-Network-Centrality-Hierarchy-R.html#tasksocial-correlations"><i class="fa fa-check"></i><b>9.2.4</b> Task/Social Correlations</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="ch9-Network-Centrality-Hierarchy-R.html"><a href="ch9-Network-Centrality-Hierarchy-R.html#centralization"><i class="fa fa-check"></i><b>9.3</b> Centralization</a></li>
<li class="chapter" data-level="9.4" data-path="ch9-Network-Centrality-Hierarchy-R.html"><a href="ch9-Network-Centrality-Hierarchy-R.html#clustering-and-hierarchy"><i class="fa fa-check"></i><b>9.4</b> Clustering and Hierarchy</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ch10-Positions-Roles-R.html"><a href="ch10-Positions-Roles-R.html"><i class="fa fa-check"></i><b>10</b> Positions and Roles</a>
<ul>
<li class="chapter" data-level="10.1" data-path="ch10-Positions-Roles-R.html"><a href="ch10-Positions-Roles-R.html#classroom-network-data"><i class="fa fa-check"></i><b>10.1</b> Classroom Network Data</a></li>
<li class="chapter" data-level="10.2" data-path="ch10-Positions-Roles-R.html"><a href="ch10-Positions-Roles-R.html#getting-the-data-ready-3"><i class="fa fa-check"></i><b>10.2</b> Getting the Data Ready</a></li>
<li class="chapter" data-level="10.3" data-path="ch10-Positions-Roles-R.html"><a href="ch10-Positions-Roles-R.html#structural-equivalence"><i class="fa fa-check"></i><b>10.3</b> Structural Equivalence</a></li>
<li class="chapter" data-level="10.4" data-path="ch10-Positions-Roles-R.html"><a href="ch10-Positions-Roles-R.html#defining-positions"><i class="fa fa-check"></i><b>10.4</b> Defining Positions</a></li>
<li class="chapter" data-level="10.5" data-path="ch10-Positions-Roles-R.html"><a href="ch10-Positions-Roles-R.html#role-analysis"><i class="fa fa-check"></i><b>10.5</b> Role Analysis</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="ch10-Positions-Roles-R.html"><a href="ch10-Positions-Roles-R.html#permuting-the-matrix-by-position"><i class="fa fa-check"></i><b>10.5.1</b> Permuting the Matrix by Position</a></li>
<li class="chapter" data-level="10.5.2" data-path="ch10-Positions-Roles-R.html"><a href="ch10-Positions-Roles-R.html#constructing-a-blockmodel"><i class="fa fa-check"></i><b>10.5.2</b> Constructing a Blockmodel</a></li>
<li class="chapter" data-level="10.5.3" data-path="ch10-Positions-Roles-R.html"><a href="ch10-Positions-Roles-R.html#plotting-a-blockmodel"><i class="fa fa-check"></i><b>10.5.3</b> Plotting a Blockmodel</a></li>
<li class="chapter" data-level="10.5.4" data-path="ch10-Positions-Roles-R.html"><a href="ch10-Positions-Roles-R.html#interpretation-of-blockmodel"><i class="fa fa-check"></i><b>10.5.4</b> Interpretation of Blockmodel</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="ch10-Positions-Roles-R.html"><a href="ch10-Positions-Roles-R.html#local-equivalence"><i class="fa fa-check"></i><b>10.6</b> Local Equivalence</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ch11-Two-mode-Networks.html"><a href="ch11-Two-mode-Networks.html"><i class="fa fa-check"></i><b>11</b> Two-mode Networks: Affilitations and Dualities</a>
<ul>
<li class="chapter" data-level="11.1" data-path="ch11-Two-mode-Networks.html"><a href="ch11-Two-mode-Networks.html#example-affiliation-data"><i class="fa fa-check"></i><b>11.1</b> Example Affiliation Data</a></li>
<li class="chapter" data-level="11.2" data-path="ch11-Two-mode-Networks.html"><a href="ch11-Two-mode-Networks.html#plotting-the-network"><i class="fa fa-check"></i><b>11.2</b> Plotting the Network</a></li>
<li class="chapter" data-level="11.3" data-path="ch11-Two-mode-Networks.html"><a href="ch11-Two-mode-Networks.html#single-mode-networks"><i class="fa fa-check"></i><b>11.3</b> Single Mode Networks</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="ch11-Two-mode-Networks.html"><a href="ch11-Two-mode-Networks.html#constructing-one-mode-projections"><i class="fa fa-check"></i><b>11.3.1</b> Constructing One-Mode Projections</a></li>
<li class="chapter" data-level="11.3.2" data-path="ch11-Two-mode-Networks.html"><a href="ch11-Two-mode-Networks.html#plotting-one-mode-projections"><i class="fa fa-check"></i><b>11.3.2</b> Plotting One-Mode Projections</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="ch11-Two-mode-Networks.html"><a href="ch11-Two-mode-Networks.html#club-to-club-network"><i class="fa fa-check"></i><b>11.4</b> Club-to-Club Network</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="ch11-Two-mode-Networks.html"><a href="ch11-Two-mode-Networks.html#centrality-1"><i class="fa fa-check"></i><b>11.4.1</b> Centrality</a></li>
<li class="chapter" data-level="11.4.2" data-path="ch11-Two-mode-Networks.html"><a href="ch11-Two-mode-Networks.html#groups"><i class="fa fa-check"></i><b>11.4.2</b> Groups</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="ch11-Two-mode-Networks.html"><a href="ch11-Two-mode-Networks.html#using-the-tnet-package"><i class="fa fa-check"></i><b>11.5</b> Using the tnet package</a></li>
<li class="chapter" data-level="11.6" data-path="ch11-Two-mode-Networks.html"><a href="ch11-Two-mode-Networks.html#racial-segregation"><i class="fa fa-check"></i><b>11.6</b> Racial Segregation</a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="ch11-Two-mode-Networks.html"><a href="ch11-Two-mode-Networks.html#proportion-of-co-membership-edges-where-students-match-on-race"><i class="fa fa-check"></i><b>11.6.1</b> Proportion of Co-membership Edges where Students Match on Race</a></li>
<li class="chapter" data-level="11.6.2" data-path="ch11-Two-mode-Networks.html"><a href="ch11-Two-mode-Networks.html#do-students-match-racially-with-at-least-one-other-student"><i class="fa fa-check"></i><b>11.6.2</b> Do Students Match Racially with at Least One Other Student?</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="ch11-Two-mode-Networks.html"><a href="ch11-Two-mode-Networks.html#club-centrality-and-attributes"><i class="fa fa-check"></i><b>11.7</b> Club Centrality and Attributes</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ch12-Networks-Culture-R.html"><a href="ch12-Networks-Culture-R.html"><i class="fa fa-check"></i><b>12</b> Networks and Culture</a></li>
<li class="chapter" data-level="" data-path="ch12-Networks-Structure-Culture-text-R.html"><a href="ch12-Networks-Structure-Culture-text-R.html"><i class="fa fa-check"></i>12, Part 1. Cultural Structures</a>
<ul>
<li class="chapter" data-level="12.1" data-path="ch12-Networks-Structure-Culture-text-R.html"><a href="ch12-Networks-Structure-Culture-text-R.html#getting-the-data-ready-4"><i class="fa fa-check"></i><b>12.1</b> Getting the Data Ready</a></li>
<li class="chapter" data-level="12.2" data-path="ch12-Networks-Structure-Culture-text-R.html"><a href="ch12-Networks-Structure-Culture-text-R.html#topic-modeling"><i class="fa fa-check"></i><b>12.2</b> Topic Modeling</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="ch12-Networks-Structure-Culture-text-R.html"><a href="ch12-Networks-Structure-Culture-text-R.html#lda-initial-model"><i class="fa fa-check"></i><b>12.2.1</b> LDA: Initial Model</a></li>
<li class="chapter" data-level="12.2.2" data-path="ch12-Networks-Structure-Culture-text-R.html"><a href="ch12-Networks-Structure-Culture-text-R.html#lda-picking-the-number-of-topics"><i class="fa fa-check"></i><b>12.2.2</b> LDA: Picking the Number of Topics</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="ch12-Networks-Structure-Culture-text-R.html"><a href="ch12-Networks-Structure-Culture-text-R.html#a-network-representation"><i class="fa fa-check"></i><b>12.3</b> A Network Representation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch12-Networks-Cultural-Spaces-CA-R.html"><a href="ch12-Networks-Cultural-Spaces-CA-R.html"><i class="fa fa-check"></i>12, Part 2. Cultural Spaces</a>
<ul>
<li class="chapter" data-level="12.4" data-path="ch12-Networks-Cultural-Spaces-CA-R.html"><a href="ch12-Networks-Cultural-Spaces-CA-R.html#correspondence-analysis"><i class="fa fa-check"></i><b>12.4</b> Correspondence Analysis</a></li>
<li class="chapter" data-level="12.5" data-path="ch12-Networks-Cultural-Spaces-CA-R.html"><a href="ch12-Networks-Cultural-Spaces-CA-R.html#number-of-dimensions"><i class="fa fa-check"></i><b>12.5</b> Number of Dimensions</a></li>
<li class="chapter" data-level="12.6" data-path="ch12-Networks-Cultural-Spaces-CA-R.html"><a href="ch12-Networks-Cultural-Spaces-CA-R.html#importance-of-rowscolumns"><i class="fa fa-check"></i><b>12.6</b> Importance of Rows/Columns</a></li>
<li class="chapter" data-level="12.7" data-path="ch12-Networks-Cultural-Spaces-CA-R.html"><a href="ch12-Networks-Cultural-Spaces-CA-R.html#hierarchical-clustering"><i class="fa fa-check"></i><b>12.7</b> Hierarchical Clustering</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="ch13-Statistical-Models-Networks-R.html"><a href="ch13-Statistical-Models-Networks-R.html"><i class="fa fa-check"></i><b>13</b> Statistical Models for Networks</a></li>
<li class="chapter" data-level="" data-path="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><a href="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><i class="fa fa-check"></i>13, Part 1. Cross-Sectional Network Models: ERGM</a>
<ul>
<li class="chapter" data-level="13.1" data-path="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><a href="ch13-Cross-Sectional-Network-Models-ERGM-R.html#setting-up-the-session-3"><i class="fa fa-check"></i><b>13.1</b> Setting up the Session</a></li>
<li class="chapter" data-level="13.2" data-path="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><a href="ch13-Cross-Sectional-Network-Models-ERGM-R.html#descriptive-statistics"><i class="fa fa-check"></i><b>13.2</b> Descriptive Statistics</a></li>
<li class="chapter" data-level="13.3" data-path="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><a href="ch13-Cross-Sectional-Network-Models-ERGM-R.html#cug-tests"><i class="fa fa-check"></i><b>13.3</b> CUG Tests</a></li>
<li class="chapter" data-level="13.4" data-path="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><a href="ch13-Cross-Sectional-Network-Models-ERGM-R.html#fitting-an-ergm"><i class="fa fa-check"></i><b>13.4</b> Fitting an ERGM</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><a href="ch13-Cross-Sectional-Network-Models-ERGM-R.html#edges-only"><i class="fa fa-check"></i><b>13.4.1</b> Edges Only</a></li>
<li class="chapter" data-level="13.4.2" data-path="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><a href="ch13-Cross-Sectional-Network-Models-ERGM-R.html#edges-and-homophily"><i class="fa fa-check"></i><b>13.4.2</b> Edges and Homophily</a></li>
<li class="chapter" data-level="13.4.3" data-path="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><a href="ch13-Cross-Sectional-Network-Models-ERGM-R.html#edges-homophily-and-node-covariates"><i class="fa fa-check"></i><b>13.4.3</b> Edges, Homophily, and Node Covariates</a></li>
<li class="chapter" data-level="13.4.4" data-path="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><a href="ch13-Cross-Sectional-Network-Models-ERGM-R.html#edges-homophily-node-covariates-and-reciprocity"><i class="fa fa-check"></i><b>13.4.4</b> Edges, Homophily, Node Covariates, and Reciprocity</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><a href="ch13-Cross-Sectional-Network-Models-ERGM-R.html#checking-model-convergence"><i class="fa fa-check"></i><b>13.5</b> Checking Model Convergence</a></li>
<li class="chapter" data-level="13.6" data-path="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><a href="ch13-Cross-Sectional-Network-Models-ERGM-R.html#goodness-of-fit"><i class="fa fa-check"></i><b>13.6</b> Goodness of Fit</a></li>
<li class="chapter" data-level="13.7" data-path="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><a href="ch13-Cross-Sectional-Network-Models-ERGM-R.html#adding-gwesp-to-the-model"><i class="fa fa-check"></i><b>13.7</b> Adding GWESP to the Model</a></li>
<li class="chapter" data-level="13.8" data-path="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><a href="ch13-Cross-Sectional-Network-Models-ERGM-R.html#simulation"><i class="fa fa-check"></i><b>13.8</b> Simulation</a></li>
<li class="chapter" data-level="13.9" data-path="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><a href="ch13-Cross-Sectional-Network-Models-ERGM-R.html#example-on-a-large-network"><i class="fa fa-check"></i><b>13.9</b> Example on a Large Network</a></li>
<li class="chapter" data-level="13.10" data-path="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><a href="ch13-Cross-Sectional-Network-Models-ERGM-R.html#ergm-on-a-valued-network"><i class="fa fa-check"></i><b>13.10</b> ERGM on a Valued Network</a>
<ul>
<li class="chapter" data-level="13.10.1" data-path="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><a href="ch13-Cross-Sectional-Network-Models-ERGM-R.html#baseline-ergm-on-valued-network"><i class="fa fa-check"></i><b>13.10.1</b> Baseline ERGM on Valued Network</a></li>
<li class="chapter" data-level="13.10.2" data-path="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><a href="ch13-Cross-Sectional-Network-Models-ERGM-R.html#adding-nodematch-and-nodefactor-terms"><i class="fa fa-check"></i><b>13.10.2</b> Adding Nodematch and Nodefactor Terms</a></li>
<li class="chapter" data-level="13.10.3" data-path="ch13-Cross-Sectional-Network-Models-ERGM-R.html"><a href="ch13-Cross-Sectional-Network-Models-ERGM-R.html#transitivity-in-valued-networks"><i class="fa fa-check"></i><b>13.10.3</b> Transitivity in Valued Networks</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch13-Longitudinal-Network-Models-STERGM-R.html"><a href="ch13-Longitudinal-Network-Models-STERGM-R.html"><i class="fa fa-check"></i>13, Part 2. Longitudinal Network Models: STERGM</a>
<ul>
<li class="chapter" data-level="13.11" data-path="ch13-Longitudinal-Network-Models-STERGM-R.html"><a href="ch13-Longitudinal-Network-Models-STERGM-R.html#getting-the-data-ready-5"><i class="fa fa-check"></i><b>13.11</b> Getting the Data Ready</a></li>
<li class="chapter" data-level="13.12" data-path="ch13-Longitudinal-Network-Models-STERGM-R.html"><a href="ch13-Longitudinal-Network-Models-STERGM-R.html#stergms"><i class="fa fa-check"></i><b>13.12</b> STERGMs</a>
<ul>
<li class="chapter" data-level="13.12.1" data-path="ch13-Longitudinal-Network-Models-STERGM-R.html"><a href="ch13-Longitudinal-Network-Models-STERGM-R.html#model-1-just-edges"><i class="fa fa-check"></i><b>13.12.1</b> Model 1: Just Edges</a></li>
<li class="chapter" data-level="13.12.2" data-path="ch13-Longitudinal-Network-Models-STERGM-R.html"><a href="ch13-Longitudinal-Network-Models-STERGM-R.html#model-2-edges-homophily-and-nodefactor"><i class="fa fa-check"></i><b>13.12.2</b> Model 2: Edges, Homophily and Nodefactor</a></li>
<li class="chapter" data-level="13.12.3" data-path="ch13-Longitudinal-Network-Models-STERGM-R.html"><a href="ch13-Longitudinal-Network-Models-STERGM-R.html#model-3-edges-nodefactor-and-seating"><i class="fa fa-check"></i><b>13.12.3</b> Model 3: Edges, Nodefactor, and Seating</a></li>
<li class="chapter" data-level="13.12.4" data-path="ch13-Longitudinal-Network-Models-STERGM-R.html"><a href="ch13-Longitudinal-Network-Models-STERGM-R.html#model-4-adding-gwesp-to-the-model"><i class="fa fa-check"></i><b>13.12.4</b> Model 4: Adding GWESP to the Model</a></li>
</ul></li>
<li class="chapter" data-level="13.13" data-path="ch13-Longitudinal-Network-Models-STERGM-R.html"><a href="ch13-Longitudinal-Network-Models-STERGM-R.html#checking-model-fit"><i class="fa fa-check"></i><b>13.13</b> Checking Model Fit</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html"><a href="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html"><i class="fa fa-check"></i>13, Part 3. Two-mode Network Models</a>
<ul>
<li class="chapter" data-level="13.14" data-path="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html"><a href="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html#affiliation-data"><i class="fa fa-check"></i><b>13.14</b> Affiliation Data</a></li>
<li class="chapter" data-level="13.15" data-path="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html"><a href="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html#ergm-on-a-two-mode-network"><i class="fa fa-check"></i><b>13.15</b> ERGM on a Two-mode Network</a>
<ul>
<li class="chapter" data-level="13.15.1" data-path="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html"><a href="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html#edges"><i class="fa fa-check"></i><b>13.15.1</b> Edges</a></li>
<li class="chapter" data-level="13.15.2" data-path="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html"><a href="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html#adjusting-for-structural-issues-gender-and-grade-specific-clubs"><i class="fa fa-check"></i><b>13.15.2</b> Adjusting for Structural Issues: Gender and Grade Specific Clubs</a></li>
</ul></li>
<li class="chapter" data-level="13.16" data-path="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html"><a href="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html#second-mode-terms"><i class="fa fa-check"></i><b>13.16</b> Second Mode Terms</a>
<ul>
<li class="chapter" data-level="13.16.1" data-path="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html"><a href="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html#nodefactor"><i class="fa fa-check"></i><b>13.16.1</b> Nodefactor</a></li>
<li class="chapter" data-level="13.16.2" data-path="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html"><a href="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html#homophily"><i class="fa fa-check"></i><b>13.16.2</b> Homophily</a></li>
</ul></li>
<li class="chapter" data-level="13.17" data-path="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html"><a href="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html#first-mode-terms"><i class="fa fa-check"></i><b>13.17</b> First Mode Terms</a></li>
<li class="chapter" data-level="13.18" data-path="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html"><a href="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html#clustering"><i class="fa fa-check"></i><b>13.18</b> Clustering</a></li>
<li class="chapter" data-level="13.19" data-path="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html"><a href="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html#two-mode-longitudinal-networks"><i class="fa fa-check"></i><b>13.19</b> Two-mode Longitudinal Networks</a>
<ul>
<li class="chapter" data-level="13.19.1" data-path="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html"><a href="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html#entry-and-exit-of-nodes"><i class="fa fa-check"></i><b>13.19.1</b> Entry and Exit of Nodes</a></li>
</ul></li>
<li class="chapter" data-level="13.20" data-path="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html"><a href="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html#stergm-on-a-two-mode-network"><i class="fa fa-check"></i><b>13.20</b> STERGM on a Two-mode Network</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch13-Relational-Event-Models-R.html"><a href="ch13-Relational-Event-Models-R.html"><i class="fa fa-check"></i>13, Part 4. Relational Event Models</a>
<ul>
<li class="chapter" data-level="13.21" data-path="ch13-Relational-Event-Models-R.html"><a href="ch13-Relational-Event-Models-R.html#getting-the-data-ready-6"><i class="fa fa-check"></i><b>13.21</b> Getting the Data Ready</a></li>
<li class="chapter" data-level="13.22" data-path="ch13-Relational-Event-Models-R.html"><a href="ch13-Relational-Event-Models-R.html#running-initial-models"><i class="fa fa-check"></i><b>13.22</b> Running Initial Models</a>
<ul>
<li class="chapter" data-level="13.22.1" data-path="ch13-Relational-Event-Models-R.html"><a href="ch13-Relational-Event-Models-R.html#intercept-only-model"><i class="fa fa-check"></i><b>13.22.1</b> Intercept Only Model</a></li>
<li class="chapter" data-level="13.22.2" data-path="ch13-Relational-Event-Models-R.html"><a href="ch13-Relational-Event-Models-R.html#adding-sender-and-receiver-effects"><i class="fa fa-check"></i><b>13.22.2</b> Adding Sender and Receiver Effects</a></li>
<li class="chapter" data-level="13.22.3" data-path="ch13-Relational-Event-Models-R.html"><a href="ch13-Relational-Event-Models-R.html#adding-covariate-event-terms"><i class="fa fa-check"></i><b>13.22.3</b> Adding Covariate Event Terms</a></li>
</ul></li>
<li class="chapter" data-level="13.23" data-path="ch13-Relational-Event-Models-R.html"><a href="ch13-Relational-Event-Models-R.html#micro-rules-of-interaction"><i class="fa fa-check"></i><b>13.23</b> Micro Rules of Interaction</a></li>
<li class="chapter" data-level="13.24" data-path="ch13-Relational-Event-Models-R.html"><a href="ch13-Relational-Event-Models-R.html#assessing-model-fit"><i class="fa fa-check"></i><b>13.24</b> Assessing Model Fit</a></li>
<li class="chapter" data-level="13.25" data-path="ch13-Relational-Event-Models-R.html"><a href="ch13-Relational-Event-Models-R.html#comparison-to-a-second-date"><i class="fa fa-check"></i><b>13.25</b> Comparison to a Second Date</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="ch14-Network-Diffusion-R.html"><a href="ch14-Network-Diffusion-R.html"><i class="fa fa-check"></i><b>14</b> Network Diffusion</a></li>
<li class="chapter" data-level="" data-path="ch14-Network-Diffusion-Infectious-Diseases-R.html"><a href="ch14-Network-Diffusion-Infectious-Diseases-R.html"><i class="fa fa-check"></i>14, Part 1. Network Diffusion: Infectious Diseases</a>
<ul>
<li class="chapter" data-level="14.1" data-path="ch14-Network-Diffusion-Infectious-Diseases-R.html"><a href="ch14-Network-Diffusion-Infectious-Diseases-R.html#reading-in-data"><i class="fa fa-check"></i><b>14.1</b> Reading in Data</a></li>
<li class="chapter" data-level="14.2" data-path="ch14-Network-Diffusion-Infectious-Diseases-R.html"><a href="ch14-Network-Diffusion-Infectious-Diseases-R.html#specifying-the-network-model"><i class="fa fa-check"></i><b>14.2</b> Specifying the Network Model</a></li>
<li class="chapter" data-level="14.3" data-path="ch14-Network-Diffusion-Infectious-Diseases-R.html"><a href="ch14-Network-Diffusion-Infectious-Diseases-R.html#estimating-the-network-model"><i class="fa fa-check"></i><b>14.3</b> Estimating the Network Model</a></li>
<li class="chapter" data-level="14.4" data-path="ch14-Network-Diffusion-Infectious-Diseases-R.html"><a href="ch14-Network-Diffusion-Infectious-Diseases-R.html#specifying-the-epidemic-model"><i class="fa fa-check"></i><b>14.4</b> Specifying the Epidemic Model</a></li>
<li class="chapter" data-level="14.5" data-path="ch14-Network-Diffusion-Infectious-Diseases-R.html"><a href="ch14-Network-Diffusion-Infectious-Diseases-R.html#running-simulations"><i class="fa fa-check"></i><b>14.5</b> Running Simulations</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="ch14-Network-Diffusion-Infectious-Diseases-R.html"><a href="ch14-Network-Diffusion-Infectious-Diseases-R.html#running-baseline-model"><i class="fa fa-check"></i><b>14.5.1</b> Running Baseline Model</a></li>
<li class="chapter" data-level="14.5.2" data-path="ch14-Network-Diffusion-Infectious-Diseases-R.html"><a href="ch14-Network-Diffusion-Infectious-Diseases-R.html#varying-network-features"><i class="fa fa-check"></i><b>14.5.2</b> Varying Network Features</a></li>
<li class="chapter" data-level="14.5.3" data-path="ch14-Network-Diffusion-Infectious-Diseases-R.html"><a href="ch14-Network-Diffusion-Infectious-Diseases-R.html#varying-epidemic-model"><i class="fa fa-check"></i><b>14.5.3</b> Varying Epidemic Model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch14-Network-Diffusion-Social-Processes-R.html"><a href="ch14-Network-Diffusion-Social-Processes-R.html"><i class="fa fa-check"></i>14, Part 2. Social Diffusion Processes</a>
<ul>
<li class="chapter" data-level="14.6" data-path="ch14-Network-Diffusion-Social-Processes-R.html"><a href="ch14-Network-Diffusion-Social-Processes-R.html#setting-up-the-session-4"><i class="fa fa-check"></i><b>14.6</b> Setting up the Session</a></li>
<li class="chapter" data-level="14.7" data-path="ch14-Network-Diffusion-Social-Processes-R.html"><a href="ch14-Network-Diffusion-Social-Processes-R.html#simple-diffusion-models"><i class="fa fa-check"></i><b>14.7</b> Simple Diffusion Models</a></li>
<li class="chapter" data-level="14.8" data-path="ch14-Network-Diffusion-Social-Processes-R.html"><a href="ch14-Network-Diffusion-Social-Processes-R.html#threshold-models-of-diffusion"><i class="fa fa-check"></i><b>14.8</b> Threshold Models of Diffusion</a>
<ul>
<li class="chapter" data-level="14.8.1" data-path="ch14-Network-Diffusion-Social-Processes-R.html"><a href="ch14-Network-Diffusion-Social-Processes-R.html#simulating-diffusion-processes-using-the-netdiffuser-package"><i class="fa fa-check"></i><b>14.8.1</b> Simulating Diffusion Processes using the netdiffuseR Package</a></li>
<li class="chapter" data-level="14.8.2" data-path="ch14-Network-Diffusion-Social-Processes-R.html"><a href="ch14-Network-Diffusion-Social-Processes-R.html#comparing-diffusion-under-different-network-and-adoption-behavior-conditions"><i class="fa fa-check"></i><b>14.8.2</b> Comparing Diffusion under Different Network and Adoption Behavior Conditions</a></li>
<li class="chapter" data-level="14.8.3" data-path="ch14-Network-Diffusion-Social-Processes-R.html"><a href="ch14-Network-Diffusion-Social-Processes-R.html#simulations-using-multiple-runs"><i class="fa fa-check"></i><b>14.8.3</b> Simulations using Multiple Runs</a></li>
</ul></li>
<li class="chapter" data-level="14.9" data-path="ch14-Network-Diffusion-Social-Processes-R.html"><a href="ch14-Network-Diffusion-Social-Processes-R.html#working-with-empirical-data"><i class="fa fa-check"></i><b>14.9</b> Working with Empirical Data</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="ch15-coevolution-networks-behaviors-siena-saom-R.html"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html"><i class="fa fa-check"></i><b>15</b> Social Influence: Coevolution of Networks and Behaviors</a>
<ul>
<li class="chapter" data-level="15.1" data-path="ch15-coevolution-networks-behaviors-siena-saom-R.html"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#reading-in-classroom-data"><i class="fa fa-check"></i><b>15.1</b> Reading in Classroom Data</a></li>
<li class="chapter" data-level="15.2" data-path="ch15-coevolution-networks-behaviors-siena-saom-R.html"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#siena-model-setup"><i class="fa fa-check"></i><b>15.2</b> SIENA Model Setup</a></li>
<li class="chapter" data-level="15.3" data-path="ch15-coevolution-networks-behaviors-siena-saom-R.html"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#model-specification"><i class="fa fa-check"></i><b>15.3</b> Model Specification</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="ch15-coevolution-networks-behaviors-siena-saom-R.html"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#model-specification-behavioral-model"><i class="fa fa-check"></i><b>15.3.1</b> Model Specification: Behavioral Model</a></li>
<li class="chapter" data-level="15.3.2" data-path="ch15-coevolution-networks-behaviors-siena-saom-R.html"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#model-specification-network-model"><i class="fa fa-check"></i><b>15.3.2</b> Model Specification: Network Model</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="ch15-coevolution-networks-behaviors-siena-saom-R.html"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#model-estimation"><i class="fa fa-check"></i><b>15.4</b> Model Estimation</a></li>
<li class="chapter" data-level="15.5" data-path="ch15-coevolution-networks-behaviors-siena-saom-R.html"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#interpretation"><i class="fa fa-check"></i><b>15.5</b> Interpretation</a>
<ul>
<li class="chapter" data-level="15.5.1" data-path="ch15-coevolution-networks-behaviors-siena-saom-R.html"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#interpreting-network-model"><i class="fa fa-check"></i><b>15.5.1</b> Interpreting Network Model</a></li>
<li class="chapter" data-level="15.5.2" data-path="ch15-coevolution-networks-behaviors-siena-saom-R.html"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#interpreting-behavioral-model"><i class="fa fa-check"></i><b>15.5.2</b> Interpreting Behavioral Model</a></li>
</ul></li>
<li class="chapter" data-level="15.6" data-path="ch15-coevolution-networks-behaviors-siena-saom-R.html"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#checking-model-fit-1"><i class="fa fa-check"></i><b>15.6</b> Checking Model Fit</a></li>
<li class="chapter" data-level="15.7" data-path="ch15-coevolution-networks-behaviors-siena-saom-R.html"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#example-with-3-time-periods"><i class="fa fa-check"></i><b>15.7</b> Example with 3 Time Periods</a>
<ul>
<li class="chapter" data-level="15.7.1" data-path="ch15-coevolution-networks-behaviors-siena-saom-R.html"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#model-specification-and-estimation"><i class="fa fa-check"></i><b>15.7.1</b> Model Specification and Estimation</a></li>
<li class="chapter" data-level="15.7.2" data-path="ch15-coevolution-networks-behaviors-siena-saom-R.html"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#time-heterogeneity"><i class="fa fa-check"></i><b>15.7.2</b> Time Heterogeneity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="how-to-cite.html"><a href="how-to-cite.html"><i class="fa fa-check"></i>How to Cite</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Network Analysis: Integrating Social Network Theory, Method, and Application with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ch15-coevolution-networks-behaviors-siena-saom-R" class="section level1 hasAnchor" number="15">
<h1><span class="header-section-number">15</span> Social Influence: Coevolution of Networks and Behaviors<a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#ch15-coevolution-networks-behaviors-siena-saom-R" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Chapter 15 covers models of social influence. We are interested in how actors come to resemble their peers in terms of behaviors (or attitudes, tastes, etc.). We will address questions of peer influence using SIENA (Simulation Investigation for Empirical Network Analysis), a stochastic actor orientated model (SAOM) designed to statistically capture the coevolution of networks and behaviors <span class="citation">(Snijders, Van de Bunt, and Steglich 2010; Steglich, Snijders, and Pearson 2010)</span>.</p>
<p>SIENA models accomplish similar tasks as the STERG models in <a href="ch13-Longitudinal-Network-Models-STERGM-R.html#ch13-Longitudinal-Network-Models-STERGM-R">Chapter 13</a>, in terms of modeling network dynamics. With SIENA, however, it becomes possible to simultaneously look at changes in behaviors and network ties, opening up questions about influence, selection and wider network processes. Thus, with SIENA, we can still predict how ties change from T to T+1, as a function of mechanisms like reciprocity, but here we can also ask about peer influence on behavior (e.g., alcohol consumption). In this way, the tutorial connects the statistical models of <a href="ch13-Statistical-Models-Networks-R.html#ch13-Statistical-Models-Networks-R">Chapter 13</a> (e.g., ERGM) to the diffusion models of <a href="ch14-Network-Diffusion-R.html#ch14-Network-Diffusion-R">Chapter 14</a>. And more substantively, we can think of SIENA as combining ERGM-like models with an explicit model of influence.</p>
<p>Empirically, we focus on problems related to peer influence and selection in the case of adolescents at school. We offer two empirical examples. The first example utilizes a small classroom-based network. The data were collected by Daniel McFarland. There are two waves of data, corresponding to semester 1 and semester 2. The key outcome of interest is how much each student liked the subject of the class, measured in both semester 1 and semester 2. There is also data on friendships for both semesters. We want to know if students tend to converge on attitudes (about how much they like the subject) with people they are friends with. We also want to see how peer influence fits into a larger picture of network change, where ties are being added and dropped over time. For example, are students similar in terms of liking the subject because of peer influence or because they select friends with similar attitudes about the class (i.e., we want to differentiate between influence and selection)? The second part of the tutorial will offer a short example focused on alcohol use.</p>
<p>It is worth noting that SIENA models are designed for fairly small networks. Researchers interested in estimating peer influence effects in larger network settings (e.g., n &gt; 2500) are likely to consider alternative approaches; such as those using more conventional regression models, which tend to scale better (see <span class="citation">Ragan et al. (2022)</span> for a comparison of conventional regression models and SIENA).</p>
<div id="reading-in-classroom-data" class="section level2 hasAnchor" number="15.1">
<h2><span class="header-section-number">15.1</span> Reading in Classroom Data<a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#reading-in-classroom-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We begin with the classroom example. Let's read in the data and get it ready for the analysis. Here we read in the semester 1 edgelist.</p>
<div class="sourceCode" id="cb1900"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1900-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1900-1" aria-hidden="true" tabindex="-1"></a>url1 <span class="ot">&lt;-</span> <span class="st">&quot;https://github.com/JeffreyAlanSmith/Integrated_Network_Science/raw/master/data/class237_sem1_edgelist.txt&quot;</span></span>
<span id="cb1900-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1900-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1900-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1900-3" aria-hidden="true" tabindex="-1"></a>sem1_edgelist <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">file =</span> url1, <span class="at">header =</span> T)</span></code></pre></div>
<div class="sourceCode" id="cb1901"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1901-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1901-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sem1_edgelist)</span></code></pre></div>
<pre><code>##   sender receiver
## 1 113214   121470
## 2 113214   125522
## 3 113214   149552
## 4 113214   122728
## 5 113214   122706
## 6 115909   127535</code></pre>
<p>The first column shows the sender of the tie and the second column shows the receiver of the tie. An edge exists between i-&gt;j if i named j as a friend. Let's read in the semester 2 edgelist.</p>
<div class="sourceCode" id="cb1903"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1903-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1903-1" aria-hidden="true" tabindex="-1"></a>url2 <span class="ot">&lt;-</span> <span class="st">&quot;https://github.com/JeffreyAlanSmith/Integrated_Network_Science/raw/master/data/class237_sem2_edgelist.txt&quot;</span></span>
<span id="cb1903-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1903-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1903-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1903-3" aria-hidden="true" tabindex="-1"></a>sem2_edgelist <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">file =</span> url2, <span class="at">header =</span> T)</span></code></pre></div>
<p>Let’s also read in the attribute file, containing nodal characteristics.</p>
<div class="sourceCode" id="cb1904"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1904-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1904-1" aria-hidden="true" tabindex="-1"></a>url3 <span class="ot">&lt;-</span> <span class="st">&quot;https://github.com/JeffreyAlanSmith/Integrated_Network_Science/raw/master/data/class237_attributes.txt&quot;</span></span>
<span id="cb1904-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1904-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1904-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1904-3" aria-hidden="true" tabindex="-1"></a>attributes <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">file =</span> url3, <span class="at">header =</span> T)</span></code></pre></div>
<div class="sourceCode" id="cb1905"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1905-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1905-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(attributes)</span></code></pre></div>
<pre><code>##      ids sem_id cls_id expected_grade like_subject had_teacher_before like_teacher course_challenging
## 1 113214      1    237              4            4                  0            3                  1
## 2 121470      1    237              3            2                  0            3                  3
## 3 122728      1    237              4            2                  0            3                  2
## 4 125522      1    237              4            3                  0            3                  4
## 5 126359      1    237              4            4                  0            4                  3
## 6 122706      1    237              4            3                  0            3                  3</code></pre>
<p>The main variables are: <code>ids</code> = id of actor; <code>sem_id</code> = semester where data comes from; expected_grade: D = 1 C = 2 B = 3 A = 4; <code>like_subject</code>: 1-4 scale, with 1 = strong dislike to 4 = like it a lot; <code>like_teacher</code>: 1-4 scale, with 1 = strong dislike to 4 = like it a lot.</p>
<p>Let’s load some useful packages. We will utilize the <strong>igraph</strong> package to start.</p>
<div class="sourceCode" id="cb1907"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1907-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1907-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph) </span>
<span id="cb1907-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1907-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape)</span>
<span id="cb1907-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1907-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div>
<p>As this is over time data, we need to be aware of the fact that nodes can come in and out of the network through time. It is possible to do the analysis while incorporating the changing composition of the network (e.g., using structural zeros for the missing cases, as in the two-mode STERGM example in <a href="ch13-Two-mode-Network-Models-ERGM-STERGM-R.html#ch13-Two-mode-Network-Models-ERGM-STERGM-R">Chapter 13</a>) and we will consider this in the second example below. Here we will keep things simple and only consider students who were in both semester 1 and semester 2. Let's find out which students were in both semesters.</p>
<div class="sourceCode" id="cb1908"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1908-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1908-1" aria-hidden="true" tabindex="-1"></a>ids_sem1 <span class="ot">&lt;-</span> attributes<span class="sc">$</span>ids[attributes<span class="sc">$</span>sem_id <span class="sc">==</span> <span class="dv">1</span>]</span>
<span id="cb1908-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1908-2" aria-hidden="true" tabindex="-1"></a>ids_sem2 <span class="ot">&lt;-</span> attributes<span class="sc">$</span>ids[attributes<span class="sc">$</span>sem_id <span class="sc">==</span> <span class="dv">2</span>]</span></code></pre></div>
<p>Here we identify the cases from semester 1 that were also in semester 2.</p>
<div class="sourceCode" id="cb1909"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1909-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1909-1" aria-hidden="true" tabindex="-1"></a>ids_keep <span class="ot">&lt;-</span> ids_sem1[ids_sem1 <span class="sc">%in%</span> ids_sem2]</span></code></pre></div>
<p>Now, let's subset the attribute data frame and the edgelists to only include those students in both semesters.</p>
<div class="sourceCode" id="cb1910"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1910-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1910-1" aria-hidden="true" tabindex="-1"></a>attributes <span class="ot">&lt;-</span> attributes[attributes<span class="sc">$</span>ids <span class="sc">%in%</span> ids_keep, ]</span>
<span id="cb1910-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1910-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1910-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1910-3" aria-hidden="true" tabindex="-1"></a>send_in_sem1 <span class="ot">&lt;-</span> sem1_edgelist[,<span class="dv">1</span>] <span class="sc">%in%</span> ids_keep</span>
<span id="cb1910-4"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1910-4" aria-hidden="true" tabindex="-1"></a>rec_in_sem1 <span class="ot">&lt;-</span> sem1_edgelist[,<span class="dv">2</span>] <span class="sc">%in%</span> ids_keep</span>
<span id="cb1910-5"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1910-5" aria-hidden="true" tabindex="-1"></a>sem1_edgelist <span class="ot">&lt;-</span> sem1_edgelist[send_in_sem1 <span class="sc">&amp;</span> rec_in_sem1, ]</span>
<span id="cb1910-6"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1910-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1910-7"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1910-7" aria-hidden="true" tabindex="-1"></a>send_in_sem2 <span class="ot">&lt;-</span> sem2_edgelist[,<span class="dv">1</span>] <span class="sc">%in%</span> ids_keep</span>
<span id="cb1910-8"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1910-8" aria-hidden="true" tabindex="-1"></a>rec_in_sem2 <span class="ot">&lt;-</span> sem2_edgelist[,<span class="dv">2</span>] <span class="sc">%in%</span> ids_keep</span>
<span id="cb1910-9"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1910-9" aria-hidden="true" tabindex="-1"></a>sem2_edgelist <span class="ot">&lt;-</span> sem2_edgelist[send_in_sem2 <span class="sc">&amp;</span> rec_in_sem2, ]</span></code></pre></div>
<p>Let's also create separate attribute data frames for semester 1 and semester 2.</p>
<div class="sourceCode" id="cb1911"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1911-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1911-1" aria-hidden="true" tabindex="-1"></a>sem1_attributes <span class="ot">&lt;-</span> attributes[attributes<span class="sc">$</span>sem_id <span class="sc">==</span> <span class="dv">1</span>, ]</span>
<span id="cb1911-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1911-2" aria-hidden="true" tabindex="-1"></a>sem2_attributes <span class="ot">&lt;-</span> attributes[attributes<span class="sc">$</span>sem_id <span class="sc">==</span> <span class="dv">2</span>, ]</span></code></pre></div>
<p>With our attribute and edgelist data frames together, we can now go ahead and construct the networks for each semester. First, we create an igraph object using the semester 1 inputs:</p>
<div class="sourceCode" id="cb1912"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1912-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1912-1" aria-hidden="true" tabindex="-1"></a>sem1_net <span class="ot">&lt;-</span> <span class="fu">graph_from_data_frame</span>(<span class="at">d =</span> sem1_edgelist, <span class="at">directed =</span> T,</span>
<span id="cb1912-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1912-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">vertices =</span> sem1_attributes)</span></code></pre></div>
<p>Now using the semester 2 inputs:</p>
<div class="sourceCode" id="cb1913"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1913-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1913-1" aria-hidden="true" tabindex="-1"></a>sem2_net <span class="ot">&lt;-</span> <span class="fu">graph_from_data_frame</span>(<span class="at">d =</span> sem2_edgelist, <span class="at">directed =</span> T,</span>
<span id="cb1913-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1913-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">vertices =</span> sem2_attributes)</span></code></pre></div>
<p>We will begin with a simple plot of the two networks. The goal is to get an initial picture of what the network looks like and whether there is any evidence of influence, in terms of liking the subject matter. For our plot, we want to color the nodes by how much they like the subject. We will code it such that blue means not liking the subject and red means liking the subject. We will set missing values to black.</p>
<div class="sourceCode" id="cb1914"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1914-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1914-1" aria-hidden="true" tabindex="-1"></a>cols_sem1 <span class="ot">&lt;-</span> <span class="fu">recode</span>(sem1_attributes<span class="sc">$</span>like_subject, <span class="at">as.factor =</span> F,</span>
<span id="cb1914-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1914-2" aria-hidden="true" tabindex="-1"></a>                    <span class="st">&quot;1 = &#39;blue&#39;; 2 = &#39;light blue&#39;; 3 = &#39;pink&#39;; </span></span>
<span id="cb1914-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1914-3" aria-hidden="true" tabindex="-1"></a><span class="st">                     4 =&#39;red&#39;; NA = &#39;black&#39;&quot;</span>)</span>
<span id="cb1914-4"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1914-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1914-5"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1914-5" aria-hidden="true" tabindex="-1"></a>cols_sem2 <span class="ot">&lt;-</span> <span class="fu">recode</span>(sem2_attributes<span class="sc">$</span>like_subject, <span class="at">as.factor =</span> F,</span>
<span id="cb1914-6"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1914-6" aria-hidden="true" tabindex="-1"></a>                    <span class="st">&quot;1 = &#39;blue&#39;; 2 = &#39;light blue&#39;; 3 = &#39;pink&#39;; </span></span>
<span id="cb1914-7"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1914-7" aria-hidden="true" tabindex="-1"></a><span class="st">                     4 = &#39;red&#39;; NA = &#39;black&#39;&quot;</span>)</span></code></pre></div>
<p>We want to plot both networks (semester 1 and semester 2) side by side. We will first get the coordinates of the nodes so the networks are aligned the same in the plot. We will base the layout on the first semester network.</p>
<div class="sourceCode" id="cb1915"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1915-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1915-1" aria-hidden="true" tabindex="-1"></a>layout <span class="ot">&lt;-</span> <span class="fu">layout.fruchterman.reingold</span>(sem1_net)</span></code></pre></div>
<p>Here we plot the semester 1 and semester 2 networks, coloring the nodes based on how much they like the subject in that semester.</p>
<div class="sourceCode" id="cb1916"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1916-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1916-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb1916-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1916-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1916-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1916-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sem1_net, <span class="at">vertex.label =</span> <span class="cn">NA</span>, <span class="at">layout =</span> layout, <span class="at">edge.arrow.size =</span> .<span class="dv">3</span>, </span>
<span id="cb1916-4"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1916-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">edge.arrow.width =</span> <span class="dv">1</span>, <span class="at">edge.color=</span><span class="st">&quot;light gray&quot;</span>,</span>
<span id="cb1916-5"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1916-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.frame.color =</span> <span class="cn">NA</span>, <span class="at">vertex.color =</span> cols_sem1) </span>
<span id="cb1916-6"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1916-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1916-7"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1916-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sem2_net, <span class="at">vertex.label =</span> <span class="cn">NA</span>, <span class="at">layout =</span> layout, <span class="at">edge.arrow.size =</span> .<span class="dv">3</span>,</span>
<span id="cb1916-8"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1916-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">edge.arrow.width =</span> <span class="dv">1</span>, <span class="at">edge.color =</span> <span class="st">&quot;light gray&quot;</span>,</span>
<span id="cb1916-9"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1916-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.frame.color =</span> <span class="cn">NA</span>, <span class="at">vertex.color =</span> cols_sem2) </span></code></pre></div>
<p><img src="Chapter15_Integrated_Network_Science_Rtutorial_coevolution_networks_behaviors_siena_files/figure-html/unnamed-chunk-15-1.png" width="768" /></p>
<p>It looks like there may be some weak clustering by how much people like the subject. It is a bit difficult to tell from the plot if people are converging with their friend's attitudes, although it does look like students who really like the subject in semester 1 tend to have more moderate views by semester 2 (moving from red to pink). That could be a sign of peer influence, but we need to examine such hypotheses more carefully.</p>
</div>
<div id="siena-model-setup" class="section level2 hasAnchor" number="15.2">
<h2><span class="header-section-number">15.2</span> SIENA Model Setup<a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#siena-model-setup" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We now move to more formally testing our hypotheses about peer influence. The question is whether students converge with their friends in terms of how much they like the subject matter. We will address this question while also considering the larger context in which actors are forming and breaking ties. With SIENA models, the basic idea is to model the coevolution of network ties and outcomes, simultaneously predicting changes in ties (what factors make a friendship more likely to be added/kept?) and changes in behaviors (what factors make it more likely to increase liking the subject?). In this way, we can explore the existence (or not) of peer influence while also controlling for nodal, dyadic and triadic processes that affect both the formation of ties and the outcome of interest (here interest in the subject). The analysis requires the <strong>RSiena</strong> package <span class="citation">(Ripley et al. 2023)</span>.</p>
<div class="sourceCode" id="cb1917"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1917-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1917-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RSiena)</span></code></pre></div>
<p><strong>RSiena</strong> requires that, before the model is run, the data be shaped into objects specifying their role in the analysis. Here we walk through that process on our classroom network data. Let's first get the network data in a matrix form. We will do this for both semester 1 and semester 2.</p>
<div class="sourceCode" id="cb1918"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1918-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1918-1" aria-hidden="true" tabindex="-1"></a>sem1_matrix <span class="ot">&lt;-</span> <span class="fu">as_adjacency_matrix</span>(<span class="at">graph =</span> sem1_net, <span class="at">sparse =</span> F)</span>
<span id="cb1918-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1918-2" aria-hidden="true" tabindex="-1"></a>sem2_matrix <span class="ot">&lt;-</span> <span class="fu">as_adjacency_matrix</span>(<span class="at">graph =</span> sem2_net, <span class="at">sparse =</span> F)</span></code></pre></div>
<p>And let's check that the row names are the same between the semester 1 and semester 2 matrices:</p>
<div class="sourceCode" id="cb1919"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1919-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1919-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">rownames</span>(sem1_matrix) <span class="sc">==</span> <span class="fu">rownames</span>(sem2_matrix))</span></code></pre></div>
<pre><code>## 
## TRUE 
##   24</code></pre>
<p>Looks good. Let's see how much change there is in terms of ties from semester 1 to semester 2.</p>
<div class="sourceCode" id="cb1921"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1921-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1921-1" aria-hidden="true" tabindex="-1"></a>tab_change <span class="ot">&lt;-</span> <span class="fu">table</span>(sem1_matrix, sem2_matrix)</span></code></pre></div>
<div class="sourceCode" id="cb1922"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1922-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1922-1" aria-hidden="true" tabindex="-1"></a>tab_change</span></code></pre></div>
<pre><code>##            sem2_matrix
## sem1_matrix   0   1
##           0 429  58
##           1  47  42</code></pre>
<p>We can see that 42 ties are stable, 58 new ties were formed and 47 were dropped. We can use this information to calculate the Jaccard index, showing how similar (or stable) the network in time 1 is to the network in time 2. Formally, the Jaccard index is defined as: N11 / (N01 + N10 + N11), where N11 is the number of ties that were in both semesters (42), N01 is the number of ties that were not in time 1 but were in time 2 (58) and N10 is the number of ties that were in time 1 but not in time 2 (47).</p>
<div class="sourceCode" id="cb1924"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1924-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1924-1" aria-hidden="true" tabindex="-1"></a><span class="dv">42</span> <span class="sc">/</span> (<span class="dv">58</span> <span class="sc">+</span> <span class="dv">47</span> <span class="sc">+</span> <span class="dv">42</span>)</span></code></pre></div>
<pre><code>## [1] 0.2857143</code></pre>
<p>We can see that .286 of the total number of ties (time 1 and time 2) were in both semesters. When the average degree is stable period to period, we want Jaccard values above .3, while values below .2 suggest there might be estimation problems. Lower Jaccard values are less problematic when average degree is increasing or decreasing. Here, we see a value slightly under .3, while the average degree has gone up somewhat between semester 1 and semester 2 (3.708 to 4.167). This suggests that we should be sensitive to possible estimation problems, but we are okay to proceed with our models. We should also keep in mind that the network itself is quite small (24 actors), which might lead to uncertain estimates.</p>
<p>As a final preliminary check, let's also make sure that the ids in the attribute data frames are sorted in the same order.</p>
<div class="sourceCode" id="cb1926"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1926-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1926-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(sem1_attributes<span class="sc">$</span>ids <span class="sc">==</span> sem2_attributes<span class="sc">$</span>ids)</span></code></pre></div>
<pre><code>## 
## TRUE 
##   24</code></pre>
<p>Looks right. We can now go ahead and start to manipulate our data, putting it in a form that the <strong>RSiena</strong> package can use. As a first step, we will gather the matrices into an array. <strong>RSiena</strong> requires that the networks be put together as an n X n X p array, where n is the size of the network and p is the number of time periods. Let's first define the size of the network (based on the number of rows in the input matrix).</p>
<div class="sourceCode" id="cb1928"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1928-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1928-1" aria-hidden="true" tabindex="-1"></a>net_size <span class="ot">&lt;-</span> <span class="fu">nrow</span>(sem1_matrix)</span></code></pre></div>
<div class="sourceCode" id="cb1929"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1929-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1929-1" aria-hidden="true" tabindex="-1"></a>net_size</span></code></pre></div>
<pre><code>## [1] 24</code></pre>
<p>Now, we can create the array based on the two matrices, setting the dimensions based on net_size, as well as the number of time periods (2).</p>
<div class="sourceCode" id="cb1931"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1931-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1931-1" aria-hidden="true" tabindex="-1"></a>sem12_array <span class="ot">&lt;-</span> <span class="fu">array</span>(<span class="fu">c</span>(sem1_matrix, sem2_matrix), </span>
<span id="cb1931-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1931-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">dim =</span> <span class="fu">c</span>(net_size, net_size, <span class="dv">2</span>))</span></code></pre></div>
<div class="sourceCode" id="cb1932"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1932-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1932-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(sem12_array)  </span></code></pre></div>
<pre><code>## [1] 24 24  2</code></pre>
<p>We can see that we have a 24 x 24 x 2 array. We can now begin to set up the model, preparing certain objects for the main <code>siena07()</code> function. Remember that SIENA models allow for the joint modeling of network change and behavior change. We thus have two kinds of models, and thus two kinds of dependent variables. As a first step, we will construct a dependent variable based on the network, so the ties (or tie change) is the outcome of interest. The function is <code>sienaDependent()</code>. The main arguments are:</p>
<ul>
<li>netarray = matrix (for behaviors) or array (for network outcomes) showing behavioral or network values to predict</li>
<li>type = type of dependent variable (e.g., behavior, oneMode)</li>
</ul>
<p>Here we include the array constructed above based on the semester 1 and semester 2 networks. The type is oneMode, indicating a one-mode network.</p>
<div class="sourceCode" id="cb1934"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1934-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1934-1" aria-hidden="true" tabindex="-1"></a>networks <span class="ot">&lt;-</span> <span class="fu">sienaDependent</span>(<span class="at">netarray =</span> sem12_array, <span class="at">type =</span> <span class="st">&quot;oneMode&quot;</span>) </span></code></pre></div>
<p>Now, we will construct the second dependent variable, based on our 'behavior' of interest, here how much they liked the subject in semester 1 and semester 2. The inputs are the over time values for liking the subject, constructed as a matrix.</p>
<div class="sourceCode" id="cb1935"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1935-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1935-1" aria-hidden="true" tabindex="-1"></a>like_subject_matrix <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">cbind</span>(sem1_attributes<span class="sc">$</span>like_subject,</span>
<span id="cb1935-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1935-2" aria-hidden="true" tabindex="-1"></a>                                       sem2_attributes<span class="sc">$</span>like_subject))</span></code></pre></div>
<div class="sourceCode" id="cb1936"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1936-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1936-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(like_subject_matrix)</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    4    3
## [2,]    2    1
## [3,]    2    3
## [4,]    3    1
## [5,]    4    3
## [6,]    3    3</code></pre>
<p>We again use the <code>sienaDependent()</code> function to construct our dependent variable, but here netarray is set to the like_subject matrix and type is set to "behavior".</p>
<div class="sourceCode" id="cb1938"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1938-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1938-1" aria-hidden="true" tabindex="-1"></a>like_subject <span class="ot">&lt;-</span> <span class="fu">sienaDependent</span>(<span class="at">netarray =</span> like_subject_matrix, </span>
<span id="cb1938-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1938-2" aria-hidden="true" tabindex="-1"></a>                               <span class="at">type =</span> <span class="st">&quot;behavior&quot;</span>) </span></code></pre></div>
<p>Let's also create an object that captures covariates (i.e., predictors) to be included in the model. This will typically be fixed characteristics, like gender and race/ethnicity. Here, we will include a covariate capturing if the students liked the teacher in semester 1. The function to create covariates is <code>coCovar()</code>.</p>
<div class="sourceCode" id="cb1939"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1939-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1939-1" aria-hidden="true" tabindex="-1"></a>like_teacher <span class="ot">&lt;-</span> <span class="fu">coCovar</span>(sem1_attributes<span class="sc">$</span>like_teacher)</span></code></pre></div>
<p>We would want to use the <code>varCovar()</code> function if the variable of interest has changing values over time. The input is an n by M - 1 matrix, where n is the number of nodes in the network and M is the number of time points (the final observation is excluded). It is only appropriate to use <code>varCovar()</code> if there are at least 3 periods of data.</p>
<p>Now, we will put the constructed objects together using a <code>sienaDataCreate()</code> function. This siena object will be one of the main inputs into the function to run the model.</p>
<div class="sourceCode" id="cb1940"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1940-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1940-1" aria-hidden="true" tabindex="-1"></a>net_behavior_covar <span class="ot">&lt;-</span> <span class="fu">sienaDataCreate</span>(networks, like_subject, like_teacher)</span></code></pre></div>
<div class="sourceCode" id="cb1941"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1941-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1941-1" aria-hidden="true" tabindex="-1"></a>net_behavior_covar </span></code></pre></div>
<pre><code>## Dependent variables:  networks, like_subject 
## Number of observations: 2 
## 
## Nodeset                  Actors 
## Number of nodes              24 
## 
## Dependent variable networks 
## Type               oneMode  
## Observations       2        
## Nodeset            Actors   
## Densities          0.16 0.18
## 
## Dependent variable like_subject
## Type               behavior    
## Observations       2           
## Nodeset            Actors      
## Range              1 - 4       
## 
## Constant covariates:  like_teacher</code></pre>
<p>We see basic information about our network, like density and number of nodes, as well as useful information about the behavior of interest (such as the range of values).</p>
</div>
<div id="model-specification" class="section level2 hasAnchor" number="15.3">
<h2><span class="header-section-number">15.3</span> Model Specification<a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#model-specification" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We now take our constructed siena object and specify the model we want to use to predict changes in ties and changes in behaviors, here about how much they like the subject. The model is based on an evaluation function, where actors evaluate adding/dropping ties and changing behavior based on the specified model. Positive coefficients suggest the change is more likely than chance expectations, while negative coefficients suggest the change is less likely. The coefficients are estimated based on the observed tendencies seen in the input data, in terms of network and behavioral change. For example, with the network model, if actors select friends with similar behaviors as themselves, we would expect a positive coefficient on the selection term. Or, for the behavior model, if actors tend to converge on behaviors with their friends, we would expect a positive peer influence term.</p>
<p><strong>RSiena</strong> works by 'building up' the model. We first get the base terms using a <code>getEffects</code>() function and then use an <code>includeEffects()</code> function to add terms to the base model. Let's start with getting the base model, with the main input as the siena object created above.</p>
<div class="sourceCode" id="cb1943"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1943-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1943-1" aria-hidden="true" tabindex="-1"></a>siena_effects <span class="ot">&lt;-</span> <span class="fu">getEffects</span>(net_behavior_covar)</span></code></pre></div>
<div class="sourceCode" id="cb1944"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1944-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1944-1" aria-hidden="true" tabindex="-1"></a>siena_effects </span></code></pre></div>
<pre><code>##   name         effectName                    include fix   test  initialValue parm
## 1 networks     basic rate parameter networks TRUE    FALSE FALSE    9.12260   0   
## 2 networks     outdegree (density)           TRUE    FALSE FALSE   -0.71940   0   
## 3 networks     reciprocity                   TRUE    FALSE FALSE    0.00000   0   
## 4 like_subject rate like_subject period 1    TRUE    FALSE FALSE    0.81028   0   
## 5 like_subject like_subject linear shape     TRUE    FALSE FALSE   -0.10773   0   
## 6 like_subject like_subject quadratic shape  TRUE    FALSE FALSE    0.00000   0</code></pre>
<p>The first thing to note is that there are two kinds of model terms here, one predicting how the network changes over time (name = networks) and one predicting how much they like the subject changes over time (name = like_subject). We can see that the network model, by default, includes a term for density, tie change (the rate of change between T1 and T2) and reciprocity. The default model for attitudes about the subject are the base rate of change for liking the subject, and linear and quadratic terms, showing tendencies for actors with too high (or low) values (compared to the mean) to increase/decrease their preferences. Now, let's start adding terms to the model.</p>
<div id="model-specification-behavioral-model" class="section level3 hasAnchor" number="15.3.1">
<h3><span class="header-section-number">15.3.1</span> Model Specification: Behavioral Model<a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#model-specification-behavioral-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>First, we will focus on the behavioral model, predicting how like_subject changes across semesters. The function to add terms is <code>includeEffects()</code>. The main arguments are:</p>
<ul>
<li>myeff = siena object of effects</li>
<li>name of term to include</li>
<li>interaction1 = siena object from which effects are being calculated</li>
<li>name = name of dependent variable for which effects are being included</li>
</ul>
<p>First, let's include a peer influence term, asking if people tend to converge on liking the subject over time. Here we add an avSim term, although there are other options to capture peer influence. avSim is the average similarity effects, showing if actors tend to have values similar to the average of their network alters. We set interaction1 = "networks" as the network data must be used to construct the effect and we set name = "like_subject" as the outcome of interest is liking the subject between semester 1 and 2.</p>
<div class="sourceCode" id="cb1946"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1946-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1946-1" aria-hidden="true" tabindex="-1"></a>siena_effects <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(siena_effects, avSim, </span>
<span id="cb1946-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1946-2" aria-hidden="true" tabindex="-1"></a>                                <span class="at">interaction1 =</span> <span class="st">&quot;networks&quot;</span>,</span>
<span id="cb1946-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1946-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">name =</span> <span class="st">&quot;like_subject&quot;</span>)  </span></code></pre></div>
<p>Now, let's include a term that captures if people with higher indegree tend to decrease/increase their liking of the subject (compared to people with lower indegree). The base term is called indeg, and we again have the same inputs for interaction1 and name as above.</p>
<div class="sourceCode" id="cb1947"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1947-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1947-1" aria-hidden="true" tabindex="-1"></a>siena_effects <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(siena_effects, indeg, </span>
<span id="cb1947-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1947-2" aria-hidden="true" tabindex="-1"></a>                                <span class="at">interaction1 =</span> <span class="st">&quot;networks&quot;</span>,</span>
<span id="cb1947-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1947-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">name =</span> <span class="st">&quot;like_subject&quot;</span>) </span></code></pre></div>
<p>It is useful to control for other individual-level characteristics that may affect the outcome of interest, here liking the subject. In this case, let's control for how much the student likes the teacher (<code>like_teacher</code>). Thus, we may think that students will increase their level of liking the subject if they like the teacher (measured in semester 1 and held fixed). The term is called effFrom. The interaction1 input is now "like_teacher" as we are interested using that variable as the predictor; name is still is equal to "like_subject" as this is the outcome of interest.</p>
<div class="sourceCode" id="cb1948"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1948-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1948-1" aria-hidden="true" tabindex="-1"></a>siena_effects <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(siena_effects, effFrom,</span>
<span id="cb1948-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1948-2" aria-hidden="true" tabindex="-1"></a>                                <span class="at">interaction1 =</span> <span class="st">&quot;like_teacher&quot;</span>, </span>
<span id="cb1948-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1948-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">name =</span> <span class="st">&quot;like_subject&quot;</span>) </span></code></pre></div>
</div>
<div id="model-specification-network-model" class="section level3 hasAnchor" number="15.3.2">
<h3><span class="header-section-number">15.3.2</span> Model Specification: Network Model<a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#model-specification-network-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Here, we will add terms to the model that predicts the evolution of friendship ties as the outcome of interest, where students form and drop ties between semester 1 and 2. There are a number of terms we could add to the model but let's focus on 4 common ones.</p>
<p>First, we often want to know if actors form (and keep) ties based on sharing some attitude or behavior of interest. In this case, we want to know if actors select friends with similar attitudes about the subject. We can think of this as selection, allowing us to include terms for both influence and selection in the model. We set interaction1 to "like_subject" and name to "networks", as the outcome of interest is the ties, rather than liking the subject (as above). The term is simX.</p>
<div class="sourceCode" id="cb1949"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1949-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1949-1" aria-hidden="true" tabindex="-1"></a>siena_effects <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(siena_effects, simX, </span>
<span id="cb1949-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1949-2" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">interaction1 =</span> <span class="st">&quot;like_subject&quot;</span>, </span>
<span id="cb1949-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1949-3" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">name =</span> <span class="st">&quot;networks&quot;</span>) </span></code></pre></div>
<p>Let's also add degree effects, showing if people with certain attributes (here liking the subject) send out more/less ties. The term is egoX and the rest is the same. This captures the effect of liking the subject on outdegree.</p>
<div class="sourceCode" id="cb1950"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1950-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1950-1" aria-hidden="true" tabindex="-1"></a>siena_effects <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(siena_effects, egoX, </span>
<span id="cb1950-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1950-2" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">interaction1 =</span> <span class="st">&quot;like_subject&quot;</span>, </span>
<span id="cb1950-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1950-3" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">name =</span> <span class="st">&quot;networks&quot;</span>) </span></code></pre></div>
<p>Here we add the analogous term for ties coming in, showing if people with certain attributes (here liking the subject) receive more/less ties. The term is altX and the rest is the same. This captures the effect of liking the subject on indegree.</p>
<div class="sourceCode" id="cb1951"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1951-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1951-1" aria-hidden="true" tabindex="-1"></a>siena_effects <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(siena_effects, altX, </span>
<span id="cb1951-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1951-2" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">interaction1 =</span> <span class="st">&quot;like_subject&quot;</span>, </span>
<span id="cb1951-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1951-3" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">name =</span> <span class="st">&quot;networks&quot;</span>)</span></code></pre></div>
<p>Finally, let's add a term for transitivity, or local clustering, in tie formation. transTrip captures the number of transitive patterns where i is tied to h and j and h is tied j.</p>
<div class="sourceCode" id="cb1952"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1952-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1952-1" aria-hidden="true" tabindex="-1"></a>siena_effects <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(siena_effects, transTrip, <span class="at">name =</span> <span class="st">&quot;networks&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb1953"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1953-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1953-1" aria-hidden="true" tabindex="-1"></a>siena_effects</span></code></pre></div>
<pre><code>##    name         effectName                             include fix   test  initialValue parm
## 1  networks     basic rate parameter networks          TRUE    FALSE FALSE    9.12260   0   
## 2  networks     outdegree (density)                    TRUE    FALSE FALSE   -0.71940   0   
## 3  networks     reciprocity                            TRUE    FALSE FALSE    0.00000   0   
## 4  networks     transitive triplets                    TRUE    FALSE FALSE    0.00000   0   
## 5  networks     like_subject alter                     TRUE    FALSE FALSE    0.00000   0   
## 6  networks     like_subject ego                       TRUE    FALSE FALSE    0.00000   0   
## 7  networks     like_subject similarity                TRUE    FALSE FALSE    0.00000   0   
## 8  like_subject rate like_subject period 1             TRUE    FALSE FALSE    0.81028   0   
## 9  like_subject like_subject linear shape              TRUE    FALSE FALSE   -0.10773   0   
## 10 like_subject like_subject quadratic shape           TRUE    FALSE FALSE    0.00000   0   
## 11 like_subject like_subject average similarity        TRUE    FALSE FALSE    0.00000   0   
## 12 like_subject like_subject indegree                  TRUE    FALSE FALSE    0.00000   0   
## 13 like_subject like_subject: effect from like_teacher TRUE    FALSE FALSE    0.00000   0</code></pre>
<p>We could include a much more complicated set of terms to the model. This is often desirable (and necessary), to answer the question of interest and to obtain a reasonable fit. See the <strong>RSiena</strong> manual for a full list and discussion of possible terms.</p>
</div>
</div>
<div id="model-estimation" class="section level2 hasAnchor" number="15.4">
<h2><span class="header-section-number">15.4</span> Model Estimation<a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#model-estimation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We will now go ahead and estimate our model. Before we can estimate the model we need to create an object of input specifications using the <code>sienaAlgorithmCreate()</code> function. There are a number of possible inputs but here we will leave most things at the defaults. We will include a MaxDegree argument, telling the model what is the max degree possible in the network. We set MaxDegree to 5 as students were restricted to naming only up to 5 friends in the classroom. We also add a seed argument to make it easier to replicate.</p>
<div class="sourceCode" id="cb1955"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1955-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1955-1" aria-hidden="true" tabindex="-1"></a>input_options <span class="ot">&lt;-</span> <span class="fu">sienaAlgorithmCreate</span>(<span class="at">projname =</span> <span class="st">&quot;class_model&quot;</span>, </span>
<span id="cb1955-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1955-2" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">MaxDegree =</span> <span class="fu">c</span>(<span class="at">networks =</span> <span class="dv">5</span>), </span>
<span id="cb1955-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1955-3" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">seed =</span> <span class="dv">30000</span>) </span></code></pre></div>
<p>Now, we are ready to estimate the model using the <code>siena07()</code> function. The main arguments are:</p>
<ul>
<li>x = object of input specifications constructed using <code>sienaAlgorithmCreate()</code></li>
<li>data = main siena object constructed from <code>sienaDataCreate()</code> function</li>
<li>effects = model effects specified using <code>includeEffects()</code> function</li>
</ul>
<p>It is also possible to specify arguments to speed up the estimation. In particular, we can tell R to use multiple processors in the estimation. The main added arguments are:</p>
<ul>
<li>useCluster = T/F; should we use multiple clusters?</li>
<li>nbrNodes = number of processors to use</li>
</ul>
<p>Here we estimate the model using 2 processors and the inputs specified above, along with the siena object and the effects object.</p>
<div class="sourceCode" id="cb1956"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1956-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1956-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">siena07</span>(<span class="at">x =</span> input_options, <span class="at">data =</span> net_behavior_covar, </span>
<span id="cb1956-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1956-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">effects =</span> siena_effects, <span class="at">useCluster =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1956-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1956-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">nbrNodes =</span> <span class="dv">2</span>) </span></code></pre></div>
<p>Let's take a look at the results.</p>
<div class="sourceCode" id="cb1957"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1957-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1957-1" aria-hidden="true" tabindex="-1"></a>mod1</span></code></pre></div>
<pre><code>## Estimates, standard errors and convergence t-ratios
## 
##                                                   Estimate   Standard   Convergence 
##                                                                Error      t-ratio   
## Network Dynamics 
##    1. rate basic rate parameter networks           9.1907  ( 1.6434   )   -0.0663   
##    2. eval outdegree (density)                    -0.1832  ( 0.7413   )   -0.0102   
##    3. eval reciprocity                             0.3977  ( 0.2482   )   -0.0088   
##    4. eval transitive triplets                     0.1643  ( 0.1151   )   -0.0103   
##    5. eval like_subject alter                     -0.1678  ( 0.2467   )    0.0013   
##    6. eval like_subject ego                       -1.0923  ( 1.3832   )   -0.0409   
##    7. eval like_subject similarity                -0.0888  ( 1.4954   )   -0.0293   
## 
## Behavior Dynamics
##    8. rate rate like_subject period 1              2.3505  ( 1.3174   )   -0.0540   
##    9. eval like_subject linear shape              -0.4566  ( 1.7687   )   -0.0074   
##   10. eval like_subject quadratic shape           -0.3407  ( 0.9653   )   -0.0990   
##   11. eval like_subject average similarity         4.9813  ( 7.0186   )    0.0161   
##   12. eval like_subject indegree                   0.0885  ( 0.4135   )   -0.0100   
##   13. eval like_subject: effect from like_teacher  0.2683  ( 0.8997   )   -0.0566   
## 
## Overall maximum convergence ratio:    0.1859 
## 
## 
## Degrees constrained to maximum values:
## networks : 5 
## 
## 
## Total of 2494 iteration steps.</code></pre>
<p>First, let's check if the model converged. The overall convergence ratio is under .25, which is considered acceptable. We can also look at the convergence ratio of each estimated parameter in the model. Here values above .1 (taking the absolute value) suggest problems with the estimation. In this case the convergence looks good and we can move ahead looking at our model results. If the model did not converge, we would likely need to rerun the model under different specifications. For example, adding/dropping terms, starting the model at better coefficients (i.e., the coefficients estimated from the previous run) and allowing for a longer run time.</p>
<p>The main items of interest in our results are the estimates and the standard errors. Note that by dividing the estimates by the standard errors we can do traditional t-tests on the coefficients. For example, we can calculate the t-statistic for reciprocity (0.3977 / 0.2482) = 1.602, suggestive of a positive, but not significant, effect of reciprocity on the formation and keeping of ties.</p>
<p>The average similarity effect captures peer influence, showing if the focal actor tends to converge with their peers on liking the subject. We can see that that the standard errors are quite high, as is the estimated peer effect. So, while there may be peer influence, the estimate is very uncertain. The network only has 24 actors, so our behavioral model might have too many terms relative to the number of actors, leading to inflated standard errors. We might try a simpler model with fewer terms in the behavioral portion of the model. Here, we will drop indegree and the main effect of liking the teacher (setting include to FALSE).</p>
<div class="sourceCode" id="cb1959"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1959-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1959-1" aria-hidden="true" tabindex="-1"></a>siena_effects <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(siena_effects, indeg, </span>
<span id="cb1959-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1959-2" aria-hidden="true" tabindex="-1"></a>                                <span class="at">interaction1 =</span> <span class="st">&quot;networks&quot;</span>,</span>
<span id="cb1959-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1959-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">name =</span> <span class="st">&quot;like_subject&quot;</span>, <span class="at">include =</span> <span class="cn">FALSE</span>) </span>
<span id="cb1959-4"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1959-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1959-5"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1959-5" aria-hidden="true" tabindex="-1"></a>siena_effects <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(siena_effects, effFrom,</span>
<span id="cb1959-6"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1959-6" aria-hidden="true" tabindex="-1"></a>                                <span class="at">interaction1 =</span> <span class="st">&quot;like_teacher&quot;</span>, </span>
<span id="cb1959-7"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1959-7" aria-hidden="true" tabindex="-1"></a>                                <span class="at">name =</span> <span class="st">&quot;like_subject&quot;</span>, <span class="at">include =</span> <span class="cn">FALSE</span>) </span></code></pre></div>
<p>We will also allow the model to run longer by increasing the number of iterations used in phase 3 of the estimation routine. We use a n3 argument here.</p>
<div class="sourceCode" id="cb1960"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1960-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1960-1" aria-hidden="true" tabindex="-1"></a>input_options <span class="ot">&lt;-</span> <span class="fu">sienaAlgorithmCreate</span>(<span class="at">projname =</span> <span class="st">&quot;class_model&quot;</span>, </span>
<span id="cb1960-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1960-2" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">MaxDegree =</span> <span class="fu">c</span>(<span class="at">networks =</span> <span class="dv">5</span>), </span>
<span id="cb1960-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1960-3" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">n3 =</span> <span class="dv">3000</span>, <span class="at">seed =</span> <span class="dv">30000</span>)</span></code></pre></div>
<p>Let’s estimate the model. We will add returnDeps = TRUE to tell siena to return the simulated networks, which will be useful when doing model fit below.</p>
<div class="sourceCode" id="cb1961"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1961-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1961-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">siena07</span>(<span class="at">x =</span> input_options, <span class="at">data =</span> net_behavior_covar, </span>
<span id="cb1961-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1961-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">effects =</span> siena_effects, <span class="at">returnDeps =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1961-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1961-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">useCluster =</span> <span class="cn">TRUE</span>, <span class="at">nbrNodes =</span> <span class="dv">2</span>) </span></code></pre></div>
<div class="sourceCode" id="cb1962"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1962-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1962-1" aria-hidden="true" tabindex="-1"></a>mod2</span></code></pre></div>
<pre><code>## Estimates, standard errors and convergence t-ratios
## 
##                                            Estimate   Standard   Convergence 
##                                                         Error      t-ratio   
## Network Dynamics 
##    1. rate basic rate parameter networks    9.2289  ( 1.7967   )   -0.0102   
##    2. eval outdegree (density)             -0.1704  ( 0.6859   )    0.0211   
##    3. eval reciprocity                      0.3990  ( 0.2431   )    0.0122   
##    4. eval transitive triplets              0.1553  ( 0.1171   )    0.0076   
##    5. eval like_subject alter              -0.1578  ( 0.2777   )    0.0163   
##    6. eval like_subject ego                -1.0739  ( 1.2577   )   -0.0103   
##    7. eval like_subject similarity         -0.0108  ( 1.6674   )   -0.0212   
## 
## Behavior Dynamics
##    8. rate rate like_subject period 1       2.2906  ( 1.2435   )   -0.0138   
##    9. eval like_subject linear shape       -0.0664  ( 0.3862   )   -0.0049   
##   10. eval like_subject quadratic shape    -0.2609  ( 0.8606   )   -0.0219   
##   11. eval like_subject average similarity  5.3366  ( 6.8374   )    0.0535   
## 
## Overall maximum convergence ratio:    0.0777 
## 
## 
## Degrees constrained to maximum values:
## networks : 5 
## 
## 
## Total of 4412 iteration steps.</code></pre>
<p>As we can see, the standard errors are still quite high and the estimates are pretty similar, even with dropping terms and increasing the number of iterations. This suggests that the limitations of the data are the likely culprit. The network is rather small (only 24 actors) and only has 2 waves, making it difficult to parse the effect of peer influence. Practically, a researcher may need to employ data on a larger network, with, ideally, more time points. We consider an example on a larger network below that has 3 waves. Before we move to that second example, let's continue with our classroom network, seeing how we can interpret the results and check model fit.</p>
</div>
<div id="interpretation" class="section level2 hasAnchor" number="15.5">
<h2><span class="header-section-number">15.5</span> Interpretation<a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#interpretation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In interpreting the coefficients, it is important to consider the form of the evaluation function specified in the model. It is also useful to distinguish between the network dynamics model and the behavioral dynamics model. We will start by interpreting the network dynamics model.</p>
<div id="interpreting-network-model" class="section level3 hasAnchor" number="15.5.1">
<h3><span class="header-section-number">15.5.1</span> Interpreting Network Model<a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#interpreting-network-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The coefficients can be understood as increasing/decreasing the ratio of the log-probability that i adds (or keeps) a tie to j compared to i adding (or keeping) a tie to h, where j and h are different nodes in the network with different attributes and structural positions relative to i. For example, we see a coefficient for reciprocity of 0.399. This would suggest that the odds of a tie from i being sent to j is exp(0.399) times higher than being sent to h, assuming that j-&gt;i exists but h-&gt;i does not.</p>
<p>We can interpret each term in an analogous fashion, although some terms offer more complicated functional forms and are thus harder to interpret. For example, some attributes, like liking the subject may be in multiple terms (indegree, outdegree, selection), making it potentially important to consider all terms together when interpreting effects.</p>
</div>
<div id="interpreting-behavioral-model" class="section level3 hasAnchor" number="15.5.2">
<h3><span class="header-section-number">15.5.2</span> Interpreting Behavioral Model<a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#interpreting-behavioral-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We now turn to the behavioral model, where we are particularly interested in peer influence effects. Note that our average similarity term had very high standard errors and we should be hesitant in pushing the interpretation of that coefficient too far, even as we use that coefficient in our calculations below. More generally, peer influence effects can be a little tricky to interpret as we need to incorporate the proper functional form used in the evaluation function and we need to include multiple terms in interpreting the effect of peer influence (in particular the linear and quadratic shape terms along with the average similarity term). Our goal here is to calculate a table of peer influence that shows how strongly students are drawn to having the same values as their peers. We will calculate the evaluation function for different students with friends who are more/less similar to them. This table of peer influence effects will aid in interpretation.</p>
<p>It is important to note that the function used to calculate the peer effects will be different, depending on the exact term used in the model. Here we will consider the evaluation function related to average similarity. A researcher can calculate the influence table on their own (see <strong>RSiena</strong> Manual) but there are now functions available from the SIENA development team to make this task much easier. As of the writing of this tutorial, these functions must be read into R separately from the base <strong>RSiena</strong> package. This can be downloaded from: <a href="https://www.stats.ox.ac.uk/~snijders/siena/InfluenceTables.r" class="uri">https://www.stats.ox.ac.uk/~snijders/siena/InfluenceTables.r</a>. Once this file is in the working directory, we can source it into R as follows:</p>
<div class="sourceCode" id="cb1964"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1964-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1964-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="at">file =</span> <span class="st">&quot;InfluenceTables.r&quot;</span>)</span></code></pre></div>
<p>The main function we will make use of is <code>influenceMatrix()</code>. The arguments are:</p>
<ul>
<li>x = estimated model</li>
<li>xd = siena network/behavior object</li>
<li>netname = network relation name</li>
<li>behname = behavioral name</li>
<li>levls = levels possible for behavioral outcome</li>
</ul>
<div class="sourceCode" id="cb1965"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1965-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1965-1" aria-hidden="true" tabindex="-1"></a>influence_matrix <span class="ot">&lt;-</span> <span class="fu">influenceMatrix</span>(<span class="at">x =</span> mod2, <span class="at">xd =</span> net_behavior_covar, </span>
<span id="cb1965-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1965-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">netname =</span> <span class="st">&quot;networks&quot;</span>, </span>
<span id="cb1965-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1965-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">behname =</span> <span class="st">&quot;like_subject&quot;</span>,</span>
<span id="cb1965-4"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1965-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">levls =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>) </span></code></pre></div>
<div class="sourceCode" id="cb1966"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1966-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1966-1" aria-hidden="true" tabindex="-1"></a>influence_matrix </span></code></pre></div>
<pre><code>##            1          2          3          4
## 1  0.8824755 -0.3803648 -2.1651001 -4.4717305
## 2 -0.8963811  1.3984919 -0.3862435 -2.6928738
## 3 -2.6752378 -0.3803648  1.3926132 -0.9140172
## 4 -4.4540944 -2.1592214 -0.3862435  0.8648395</code></pre>
<p>The columns correspond to the potential behavior of ego (values 1 through 4 corresponding to how much they like the subject). The rows correspond to a given set of behaviors of the alters. The values in the matrix contain the contribution to the evaluation function, showing the relative attractiveness of ego's behavior (given a set of alter behavior, on the row). Looking at the first row, we see that for an ego with all friends who have a value of 1, the most attractive option is also to have a value of 1. Compare the positive value in the first column, 0.8825, to the negative value in column 4, -4.4717 (i.e., taking a value of 4 when everyone else has a value of 1). We can use this table to see how much having all of one's friends like the subject increases the odds of a student increasing how much they like the subject. For example, if all of ego's friends had a value of 2 (row 2) and ego had a value of 1, the odds of ending up at a 2 is 9.923 times higher than staying a 1: <code>exp(1.3985) / exp(-0.8964)</code> = 9.923. This is evidence of peer influence, but we must, again, remember that our estimated parameter was quite uncertain, and thus the estimates in this table are quite uncertain.</p>
</div>
</div>
<div id="checking-model-fit-1" class="section level2 hasAnchor" number="15.6">
<h2><span class="header-section-number">15.6</span> Checking Model Fit<a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#checking-model-fit-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Finally, it is a good idea (like with ERGM) to check the fit of the model. Here, we ask if the estimated model can reproduce key features of the network and behaviors. The basic idea is to simulate from the model and then check if the networks and behavioral distributions based on the model match the observed data.</p>
<p>Let's first see if the model is reproducing the indegree distribution. The function is <code>sienaGOF()</code>. The arguments are:</p>
<ul>
<li>sienaFitObject = model,</li>
<li>auxiliaryFunction = function to calculate</li>
<li>varName = network relation or behavior of interest</li>
</ul>
<div class="sourceCode" id="cb1968"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1968-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1968-1" aria-hidden="true" tabindex="-1"></a>gof1 <span class="ot">&lt;-</span> <span class="fu">sienaGOF</span>(<span class="at">sienaFitObject =</span> mod2, </span>
<span id="cb1968-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1968-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">auxiliaryFunction =</span> IndegreeDistribution, </span>
<span id="cb1968-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1968-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">verbose =</span> <span class="cn">TRUE</span>, <span class="at">join =</span> <span class="cn">TRUE</span>, <span class="at">varName =</span> <span class="st">&quot;networks&quot;</span>) </span></code></pre></div>
<p>And now let's plot the results.</p>
<div class="sourceCode" id="cb1969"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1969-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1969-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(gof1)   </span></code></pre></div>
<p><img src="Chapter15_Integrated_Network_Science_Rtutorial_coevolution_networks_behaviors_siena_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<p>We are looking for any large deviations between the observed and simulated networks. Low p-values would indicate a potential problem. The fit looks okay here. And now we look at the triad census.</p>
<div class="sourceCode" id="cb1970"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1970-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1970-1" aria-hidden="true" tabindex="-1"></a>gof2 <span class="ot">&lt;-</span> <span class="fu">sienaGOF</span>(<span class="at">sienaFitObject =</span> mod2, <span class="at">auxiliaryFunction =</span> TriadCensus, </span>
<span id="cb1970-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1970-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">verbose =</span> <span class="cn">TRUE</span>, <span class="at">join =</span> <span class="cn">TRUE</span>, <span class="at">varName =</span> <span class="st">&quot;networks&quot;</span>)</span></code></pre></div>
<p>We will set center and scale to TRUE to make a better-looking plot:</p>
<div class="sourceCode" id="cb1971"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1971-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1971-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(gof2, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">TRUE</span>)   </span></code></pre></div>
<p><img src="Chapter15_Integrated_Network_Science_Rtutorial_coevolution_networks_behaviors_siena_files/figure-html/unnamed-chunk-57-1.png" width="672" /></p>
<p>Again, the fit looks okay. Here we look at the overall fit of the behavior distribution.</p>
<div class="sourceCode" id="cb1972"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1972-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1972-1" aria-hidden="true" tabindex="-1"></a>gof_behaviour <span class="ot">&lt;-</span> <span class="fu">sienaGOF</span>(<span class="at">sienaFitObject =</span> mod2, </span>
<span id="cb1972-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1972-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">auxiliaryFunction =</span> BehaviorDistribution,</span>
<span id="cb1972-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1972-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">varName =</span> <span class="st">&quot;like_subject&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb1973"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1973-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1973-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(gof_behaviour)</span></code></pre></div>
<p><img src="Chapter15_Integrated_Network_Science_Rtutorial_coevolution_networks_behaviors_siena_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<p>The fit looks okay. Note that <strong>RSiena</strong> makes it possible to add other, user-defined statistics that are not currently defined in the <strong>RSiena</strong> package (e.g., we may want to look at fit for distance). See <code>?sienaGOF-auxiliary</code> for examples.</p>
</div>
<div id="example-with-3-time-periods" class="section level2 hasAnchor" number="15.7">
<h2><span class="header-section-number">15.7</span> Example with 3 Time Periods<a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#example-with-3-time-periods" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We now turn to a short example with 3 time periods, to see how the mechanics and interpretation change in cases where there are more than 2 time periods. The network is also larger than in our first example. In this case, we will make use of one of the example data sets from the siena website, the glasgow friendship data: <a href="https://www.stats.ox.ac.uk/~snijders/siena/Glasgow_data.htm" class="uri">https://www.stats.ox.ac.uk/~snijders/siena/Glasgow_data.htm</a>. The data are based on students in a secondary school in Glasgow. The data contain friendship information, demographic information and substance use data for three waves. Here we focus on alcohol use. Let's read in the data.</p>
<div class="sourceCode" id="cb1974"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1974-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1974-1" aria-hidden="true" tabindex="-1"></a>url4 <span class="ot">&lt;-</span> <span class="st">&quot;https://github.com/JeffreyAlanSmith/Integrated_Network_Science/raw/master/data/Glasgow-friendship.RData&quot;</span></span>
<span id="cb1974-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1974-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1974-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1974-3" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="at">description =</span> url4))</span>
<span id="cb1974-4"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1974-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1974-5"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1974-5" aria-hidden="true" tabindex="-1"></a>url5 <span class="ot">&lt;-</span> <span class="st">&quot;https://github.com/JeffreyAlanSmith/Integrated_Network_Science/raw/master/data/Glasgow-substances.RData&quot;</span></span>
<span id="cb1974-6"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1974-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1974-7"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1974-7" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="at">description =</span> url5))</span>
<span id="cb1974-8"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1974-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1974-9"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1974-9" aria-hidden="true" tabindex="-1"></a>url6 <span class="ot">&lt;-</span> <span class="st">&quot;https://github.com/JeffreyAlanSmith/Integrated_Network_Science/raw/master/data/Glasgow-demographic.RData&quot;</span></span>
<span id="cb1974-10"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1974-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1974-11"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1974-11" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="at">description =</span> url6))</span></code></pre></div>
<p>Let's get the objects together to run the model. The friendship data is housed in friendship.1, friendship.2 and friendship.3. Each is a matrix showing if there is a tie between i and j, where 0 = no tie; 1 = best friend; 2 = friend; 10 = structural absence of tie (as at least one student in the ij pair was not in the school for that wave). There are also some NAs in the matrices, indicating that there is no information on whether a tie exists between i and j. Let's look at a piece of the matrix:</p>
<div class="sourceCode" id="cb1975"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1975-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1975-1" aria-hidden="true" tabindex="-1"></a>friendship<span class="fl">.1</span>[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>] </span></code></pre></div>
<pre><code>##      s001 s002 s003 s004 s005 s006 s007 s008 s009 s010
## s001    0    0    0    0    0    0    0    0    0    0
## s002    0    0    0    0    0    0    0    0    0    0
## s003    0    0    0    0    0    0    0    0    0    0
## s004    0    0    0    0    0    0    0    2    0    0
## s005    0    0    0    0    0    2    0    0    0    2
## s006    0    0    0    0    0    0    0    0    0    0
## s007    0    0    0    2    0    0    0    0    0    0
## s008    0    0    0    2    0    0    2    0    0    0
## s009    0    0    0    0    0    0    0    0    0    0
## s010    0    0    0    0    2    0    0    0    0    0</code></pre>
<p>The alcohol data is housed in alcohol.</p>
<div class="sourceCode" id="cb1977"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1977-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1977-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(alcohol)</span></code></pre></div>
<pre><code>##      t1 t2 t3
## s001  3  1  3
## s002 NA NA NA
## s003  2  2  2
## s004  2  2  3
## s005  2  3  3
## s006  3  2  5</code></pre>
<p>The data show the value on alcohol use in the three waves of data: 1 = none; 2 = once or twice a year; 3 = once a month; 4 = once a week; 5 = more than once a week.</p>
<p>There is a moderate amount of missing data in a given wave, around 13% missing on key variables, like alcohol use (excluding students who were not in the school for that wave, having entered at a later wave or already exiting the school; this is about 4% of students). It is generally considered problematic if one has more than 20% missing data. See <strong>RSiena</strong> manual for more details.</p>
<p>For this analysis, we will keep all students who were ever in the school, thus allowing students to join and leave the network through time. This is handled by the structural zeros in the matrices, showing that no tie was possible from i to j and j to i because (at least) one of the students was not in the school for that wave. This is analogous to how we treated the longitudinal data in the two-mode ERGM tutorial. In <strong>RSiena</strong>, a value of 10 (in the input matrix) is a special value, indicating a structural zero is present. This is already properly coded in the friendship matrices. The model will thus be conditioned on the structural zeros present in the data. Similarly, we will not exclude cases with missing data, keeping the missing values as NAs (these values will be treated as non-informative during estimation).</p>
<p>Let's begin by turning all of the 2s into 1s, so the matrix is just friend or no friend (i.e., we no longer make a distinction between best friend and friend). Values of 10 (structural zeros) will be kept at 10.</p>
<div class="sourceCode" id="cb1979"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1979-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1979-1" aria-hidden="true" tabindex="-1"></a>friendship<span class="fl">.1</span>[friendship<span class="fl">.1</span> <span class="sc">==</span> <span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb1979-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1979-2" aria-hidden="true" tabindex="-1"></a>friendship<span class="fl">.2</span>[friendship<span class="fl">.2</span> <span class="sc">==</span> <span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb1979-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1979-3" aria-hidden="true" tabindex="-1"></a>friendship<span class="fl">.3</span>[friendship<span class="fl">.3</span> <span class="sc">==</span> <span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span></code></pre></div>
<p>Here we take those matrices and put them into a single array.</p>
<div class="sourceCode" id="cb1980"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1980-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1980-1" aria-hidden="true" tabindex="-1"></a>net_size_ex2 <span class="ot">&lt;-</span> <span class="fu">nrow</span>(friendship<span class="fl">.1</span>)</span>
<span id="cb1980-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1980-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1980-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1980-3" aria-hidden="true" tabindex="-1"></a>net_array <span class="ot">&lt;-</span> <span class="fu">array</span>(<span class="fu">c</span>(friendship<span class="fl">.1</span>, friendship<span class="fl">.2</span>, friendship<span class="fl">.3</span>), </span>
<span id="cb1980-4"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1980-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">dim =</span> <span class="fu">c</span>(net_size_ex2, net_size_ex2, <span class="dv">3</span>))</span></code></pre></div>
<div class="sourceCode" id="cb1981"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1981-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1981-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(net_array)  </span></code></pre></div>
<pre><code>## [1] 160 160   3</code></pre>
<p>We have a 160 x 160 X 3 array. We can now create a siena object based on the array of network data.</p>
<div class="sourceCode" id="cb1983"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1983-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1983-1" aria-hidden="true" tabindex="-1"></a>friendship <span class="ot">&lt;-</span> <span class="fu">sienaDependent</span>(<span class="at">netarray =</span> net_array, <span class="at">type =</span> <span class="st">&quot;oneMode&quot;</span>) </span></code></pre></div>
<div class="sourceCode" id="cb1984"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1984-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1984-1" aria-hidden="true" tabindex="-1"></a>friendship</span></code></pre></div>
<pre><code>## Type         oneMode              
## Observations 3                    
## Nodeset      Actors (160 elements)</code></pre>
<p>Now we deal with the behavioral outcome of interest, alcohol use. Here we create the behavioral siena object.</p>
<div class="sourceCode" id="cb1986"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1986-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1986-1" aria-hidden="true" tabindex="-1"></a>alcohol_depvar <span class="ot">&lt;-</span> <span class="fu">sienaDependent</span>(<span class="at">netarray =</span> alcohol, <span class="at">type =</span> <span class="st">&quot;behavior&quot;</span>) </span></code></pre></div>
<div class="sourceCode" id="cb1987"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1987-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1987-1" aria-hidden="true" tabindex="-1"></a>alcohol_depvar</span></code></pre></div>
<pre><code>## Type         behavior             
## Observations 3                    
## Nodeset      Actors (160 elements)</code></pre>
<p>Let's also create some covariates to be included in the model. Here we create a variable for gender. Gender is housed as sex.F. 1 = boys; 2 = girls</p>
<div class="sourceCode" id="cb1989"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1989-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1989-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sex.F)</span></code></pre></div>
<pre><code>## s001 s002 s003 s004 s005 s006 
##    2    1    2    1    1    1</code></pre>
<p>Let’s create a covariate object:</p>
<div class="sourceCode" id="cb1991"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1991-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1991-1" aria-hidden="true" tabindex="-1"></a>gender <span class="ot">&lt;-</span> <span class="fu">coCovar</span>(sex.F) </span></code></pre></div>
<p>Here we put the constructed objects together using a <code>sienaDataCreate()</code> function:</p>
<div class="sourceCode" id="cb1992"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1992-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1992-1" aria-hidden="true" tabindex="-1"></a>friend_behavior_covar <span class="ot">&lt;-</span> <span class="fu">sienaDataCreate</span>(friendship, alcohol_depvar, gender)</span></code></pre></div>
<div class="sourceCode" id="cb1993"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1993-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1993-1" aria-hidden="true" tabindex="-1"></a>friend_behavior_covar</span></code></pre></div>
<pre><code>## Dependent variables:  friendship, alcohol_depvar 
## Number of observations: 3 
## 
## Nodeset                  Actors 
## Number of nodes             160 
## 
## Dependent variable friendship      
## Type               oneMode         
## Observations       3               
## Nodeset            Actors          
## Densities          0.023 0.021 0.02
## 
## Dependent variable alcohol_depvar
## Type               behavior      
## Observations       3             
## Nodeset            Actors        
## Range              1 - 5         
## 
## Constant covariates:  gender</code></pre>
<div id="model-specification-and-estimation" class="section level3 hasAnchor" number="15.7.1">
<h3><span class="header-section-number">15.7.1</span> Model Specification and Estimation<a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#model-specification-and-estimation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now, we specify our model of interest. We want to run a similar model as above, where the focus is on selection/influence effects, here for drinking behavior. We start with the base model.</p>
<div class="sourceCode" id="cb1995"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1995-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1995-1" aria-hidden="true" tabindex="-1"></a>siena_effects_3wave_example <span class="ot">&lt;-</span> <span class="fu">getEffects</span>(friend_behavior_covar) </span></code></pre></div>
<div class="sourceCode" id="cb1996"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1996-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1996-1" aria-hidden="true" tabindex="-1"></a>siena_effects_3wave_example </span></code></pre></div>
<pre><code>##   name           effectName                          include fix   test  initialValue parm
## 1 friendship     constant friendship rate (period 1) TRUE    FALSE FALSE    7.41692   0   
## 2 friendship     constant friendship rate (period 2) TRUE    FALSE FALSE    6.16651   0   
## 3 friendship     outdegree (density)                 TRUE    FALSE FALSE   -1.66821   0   
## 4 friendship     reciprocity                         TRUE    FALSE FALSE    0.00000   0   
## 5 alcohol_depvar rate alcohol_depvar (period 1)      TRUE    FALSE FALSE    0.76577   0   
## 6 alcohol_depvar rate alcohol_depvar (period 2)      TRUE    FALSE FALSE    1.15233   0   
## 7 alcohol_depvar alcohol_depvar linear shape         TRUE    FALSE FALSE    0.35525   0   
## 8 alcohol_depvar alcohol_depvar quadratic shape      TRUE    FALSE FALSE    0.00000   0</code></pre>
<p>Note that we now have rate parameters (controlling for change in ties over time) for T1 to T2 and T2 to T3. Now we add a term for peer influence, as before, using avSim (do people tend to move towards their friends drinking behavior?)</p>
<div class="sourceCode" id="cb1998"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1998-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1998-1" aria-hidden="true" tabindex="-1"></a>siena_effects_3wave_example <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(siena_effects_3wave_example, </span>
<span id="cb1998-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1998-2" aria-hidden="true" tabindex="-1"></a>                                              avSim, </span>
<span id="cb1998-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1998-3" aria-hidden="true" tabindex="-1"></a>                                              <span class="at">interaction1 =</span> <span class="st">&quot;friendship&quot;</span>, </span>
<span id="cb1998-4"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1998-4" aria-hidden="true" tabindex="-1"></a>                                              <span class="at">name =</span> <span class="st">&quot;alcohol_depvar&quot;</span>)</span></code></pre></div>
<p>Also, let's include a term that controls for the main effect of gender on drinking behavior.</p>
<div class="sourceCode" id="cb1999"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1999-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1999-1" aria-hidden="true" tabindex="-1"></a>siena_effects_3wave_example <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(siena_effects_3wave_example, </span>
<span id="cb1999-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1999-2" aria-hidden="true" tabindex="-1"></a>                                              effFrom, </span>
<span id="cb1999-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1999-3" aria-hidden="true" tabindex="-1"></a>                                              <span class="at">interaction1 =</span> <span class="st">&quot;gender&quot;</span>, </span>
<span id="cb1999-4"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb1999-4" aria-hidden="true" tabindex="-1"></a>                                              <span class="at">name =</span> <span class="st">&quot;alcohol_depvar&quot;</span>)</span></code></pre></div>
<p>Now, we include terms that predict friendship ties as the outcome of interest, where students form and drop ties between T1 and T2 and T2 and T3. We will include outdegree and indegree effects for drinking (do people who drink send out/receive more ties?).</p>
<div class="sourceCode" id="cb2000"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2000-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2000-1" aria-hidden="true" tabindex="-1"></a>siena_effects_3wave_example <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(siena_effects_3wave_example, </span>
<span id="cb2000-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2000-2" aria-hidden="true" tabindex="-1"></a>                                              egoX, </span>
<span id="cb2000-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2000-3" aria-hidden="true" tabindex="-1"></a>                                              <span class="at">interaction1 =</span> <span class="st">&quot;alcohol_depvar&quot;</span>, </span>
<span id="cb2000-4"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2000-4" aria-hidden="true" tabindex="-1"></a>                                              <span class="at">name =</span> <span class="st">&quot;friendship&quot;</span>)</span>
<span id="cb2000-5"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2000-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2000-6"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2000-6" aria-hidden="true" tabindex="-1"></a>siena_effects_3wave_example <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(siena_effects_3wave_example, </span>
<span id="cb2000-7"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2000-7" aria-hidden="true" tabindex="-1"></a>                                              altX, </span>
<span id="cb2000-8"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2000-8" aria-hidden="true" tabindex="-1"></a>                                              <span class="at">interaction1 =</span> <span class="st">&quot;alcohol_depvar&quot;</span>, </span>
<span id="cb2000-9"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2000-9" aria-hidden="true" tabindex="-1"></a>                                              <span class="at">name =</span> <span class="st">&quot;friendship&quot;</span>)</span></code></pre></div>
<p>Now we include a term for selection on drinking behavior (do people tend to form and maintain ties with people with similar drinking behavior?)</p>
<div class="sourceCode" id="cb2001"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2001-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2001-1" aria-hidden="true" tabindex="-1"></a>siena_effects_3wave_example <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(siena_effects_3wave_example, </span>
<span id="cb2001-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2001-2" aria-hidden="true" tabindex="-1"></a>                                              simX,  </span>
<span id="cb2001-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2001-3" aria-hidden="true" tabindex="-1"></a>                                              <span class="at">interaction1 =</span> <span class="st">&quot;alcohol_depvar&quot;</span>, </span>
<span id="cb2001-4"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2001-4" aria-hidden="true" tabindex="-1"></a>                                              <span class="at">name =</span> <span class="st">&quot;friendship&quot;</span>)</span></code></pre></div>
<p>And now we add a term capturing the tendency for transitive closure in tie formation.</p>
<div class="sourceCode" id="cb2002"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2002-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2002-1" aria-hidden="true" tabindex="-1"></a>siena_effects_3wave_example <span class="ot">&lt;-</span> <span class="fu">includeEffects</span>(siena_effects_3wave_example, </span>
<span id="cb2002-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2002-2" aria-hidden="true" tabindex="-1"></a>                                              transTrip, <span class="at">name =</span> <span class="st">&quot;friendship&quot;</span>)</span></code></pre></div>
<p>Let's take a look at the model effects:</p>
<div class="sourceCode" id="cb2003"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2003-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2003-1" aria-hidden="true" tabindex="-1"></a>siena_effects_3wave_example</span></code></pre></div>
<pre><code>##    name           effectName                          include fix   test  initialValue parm
## 1  friendship     constant friendship rate (period 1) TRUE    FALSE FALSE    7.41692   0   
## 2  friendship     constant friendship rate (period 2) TRUE    FALSE FALSE    6.16651   0   
## 3  friendship     outdegree (density)                 TRUE    FALSE FALSE   -1.66821   0   
## 4  friendship     reciprocity                         TRUE    FALSE FALSE    0.00000   0   
## 5  friendship     transitive triplets                 TRUE    FALSE FALSE    0.00000   0   
## 6  friendship     alcohol_depvar alter                TRUE    FALSE FALSE    0.00000   0   
## 7  friendship     alcohol_depvar ego                  TRUE    FALSE FALSE    0.00000   0   
## 8  friendship     alcohol_depvar similarity           TRUE    FALSE FALSE    0.00000   0   
## 9  alcohol_depvar rate alcohol_depvar (period 1)      TRUE    FALSE FALSE    0.76577   0   
## 10 alcohol_depvar rate alcohol_depvar (period 2)      TRUE    FALSE FALSE    1.15233   0   
## 11 alcohol_depvar alcohol_depvar linear shape         TRUE    FALSE FALSE    0.35525   0   
## 12 alcohol_depvar alcohol_depvar quadratic shape      TRUE    FALSE FALSE    0.00000   0   
## 13 alcohol_depvar alcohol_depvar average similarity   TRUE    FALSE FALSE    0.00000   0   
## 14 alcohol_depvar alcohol_depvar: effect from gender  TRUE    FALSE FALSE    0.00000   0</code></pre>
<p>Here we set up our control inputs. We set the max degree to 6 as students were limited to naming 6 friends.</p>
<div class="sourceCode" id="cb2005"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2005-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2005-1" aria-hidden="true" tabindex="-1"></a>input_options_3wave <span class="ot">&lt;-</span> <span class="fu">sienaAlgorithmCreate</span>(<span class="at">MaxDegree =</span> <span class="fu">c</span>(<span class="at">friendship =</span> <span class="dv">6</span>),</span>
<span id="cb2005-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2005-2" aria-hidden="true" tabindex="-1"></a>                                            <span class="at">n3 =</span> <span class="dv">3000</span>, <span class="at">seed =</span> <span class="dv">5000</span>) </span></code></pre></div>
<p>And now we estimate the model.</p>
<div class="sourceCode" id="cb2006"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2006-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2006-1" aria-hidden="true" tabindex="-1"></a>mod1_3wave_example <span class="ot">&lt;-</span> <span class="fu">siena07</span>(input_options_3wave, </span>
<span id="cb2006-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2006-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">data =</span> friend_behavior_covar, </span>
<span id="cb2006-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2006-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">effects =</span> siena_effects_3wave_example, </span>
<span id="cb2006-4"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2006-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">returnDeps =</span> <span class="cn">TRUE</span>, <span class="at">initC =</span> <span class="cn">TRUE</span>, </span>
<span id="cb2006-5"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2006-5" aria-hidden="true" tabindex="-1"></a>                              <span class="at">useCluster =</span> <span class="cn">TRUE</span>, <span class="at">nbrNodes =</span> <span class="dv">2</span>) </span></code></pre></div>
<div class="sourceCode" id="cb2007"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2007-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2007-1" aria-hidden="true" tabindex="-1"></a>mod1_3wave_example</span></code></pre></div>
<pre><code>## Estimates, standard errors and convergence t-ratios
## 
##                                                Estimate   Standard   Convergence 
##                                                             Error      t-ratio   
## Network Dynamics 
##    1. rate constant friendship rate (period 1) 15.2825  ( 1.7375   )   -0.0032   
##    2. rate constant friendship rate (period 2) 11.8442  ( 1.2779   )   -0.0213   
##    3. eval outdegree (density)                 -2.5172  ( 0.0492   )   -0.0171   
##    4. eval reciprocity                          2.0224  ( 0.0939   )   -0.0151   
##    5. eval transitive triplets                  0.5646  ( 0.0232   )   -0.0366   
##    6. eval alcohol_depvar alter                -0.0407  ( 0.0612   )    0.0092   
##    7. eval alcohol_depvar ego                   0.0349  ( 0.0651   )    0.0384   
##    8. eval alcohol_depvar similarity            0.7936  ( 0.3594   )   -0.0434   
## 
## Behavior Dynamics
##    9. rate rate alcohol_depvar (period 1)       1.6392  ( 0.2958   )    0.0331   
##   10. rate rate alcohol_depvar (period 2)       2.7722  ( 0.5513   )    0.0551   
##   11. eval alcohol_depvar linear shape          0.4561  ( 0.1467   )    0.0343   
##   12. eval alcohol_depvar quadratic shape       0.0623  ( 0.0997   )    0.0315   
##   13. eval alcohol_depvar average similarity    7.1645  ( 2.2501   )   -0.0708   
##   14. eval alcohol_depvar: effect from gender   0.0497  ( 0.2012   )   -0.0220   
## 
## Overall maximum convergence ratio:    0.1194 
## 
## 
## Degrees constrained to maximum values:
## friendship : 6 
## 
## 
## Total of 5224 iteration steps.</code></pre>
<p>The first thing we see is that the model appears to have converged (looking at the overall convergence ratio and the t-ratios for each term). Looking at the estimated model, we can see that a model with three time periods looks better behaved. The standard errors tend to be lower, most noticeably for the peer influence (average similarity) coefficient. The estimate on average similarity (7.1645) is higher than what we saw above and the standard error is over 3 times smaller. The effect for peer influence is clearly significant here (with a t-statistic of: 3.184, 7.1645 / 2.2501). We also see that reciprocity is quite strong, as is the tendency for transitive relations. We also see that there is selection on alcohol use (a coefficient of 0.7936 and a standard error of 0.3594 for similarity), suggesting that not only do students tend to converge to the behaviors of their peers, they also tend to seek out those with similar drinking behavior. Again, we can use the <code>influenceMatrix()</code> function to get the full picture of how influence operates in the network in terms of alcohol use.</p>
<div class="sourceCode" id="cb2009"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2009-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2009-1" aria-hidden="true" tabindex="-1"></a>influence_matrix_3wave <span class="ot">&lt;-</span> <span class="fu">influenceMatrix</span>(<span class="at">x =</span> mod1_3wave_example, </span>
<span id="cb2009-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2009-2" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">xd =</span> friend_behavior_covar, </span>
<span id="cb2009-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2009-3" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">netname =</span> <span class="st">&quot;friendship&quot;</span>, </span>
<span id="cb2009-4"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2009-4" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">behname =</span> <span class="st">&quot;alcohol_depvar&quot;</span>, </span>
<span id="cb2009-5"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2009-5" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">levls =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) </span></code></pre></div>
<div class="sourceCode" id="cb2010"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2010-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2010-1" aria-hidden="true" tabindex="-1"></a>influence_matrix_3wave</span></code></pre></div>
<pre><code>##            1          2          3          4          5
## 1  1.3703344 -0.1540429 -1.5537744 -2.8288600 -3.9792997
## 2 -0.4208021  1.6370936  0.2373621 -1.0377235 -2.1881631
## 3 -2.2119386 -0.1540429  2.0284986  0.7534131 -0.3970266
## 4 -4.0030751 -1.9451794  0.2373621  2.5445496  1.3941099
## 5 -5.7942116 -3.7363160 -1.5537744  0.7534131  3.1852464</code></pre>
<p>We can also take a quick look at goodness of fit, here in terms of the indegree distribution.</p>
<div class="sourceCode" id="cb2012"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2012-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2012-1" aria-hidden="true" tabindex="-1"></a>gof1 <span class="ot">&lt;-</span> <span class="fu">sienaGOF</span>(mod1_3wave_example, IndegreeDistribution, </span>
<span id="cb2012-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2012-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">verbose =</span> <span class="cn">TRUE</span>, <span class="at">join =</span> <span class="cn">TRUE</span>, <span class="at">varName =</span> <span class="st">&quot;friendship&quot;</span>) </span></code></pre></div>
<div class="sourceCode" id="cb2013"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2013-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2013-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(gof1)       </span></code></pre></div>
<p><img src="Chapter15_Integrated_Network_Science_Rtutorial_coevolution_networks_behaviors_siena_files/figure-html/unnamed-chunk-88-1.png" width="672" /></p>
<p>Here we look at the overall fit of the behavior distribution.</p>
<div class="sourceCode" id="cb2014"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2014-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2014-1" aria-hidden="true" tabindex="-1"></a>gof_behaviour <span class="ot">&lt;-</span> <span class="fu">sienaGOF</span>(mod1_3wave_example, BehaviorDistribution,</span>
<span id="cb2014-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2014-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">varName =</span> <span class="st">&quot;alcohol_depvar&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb2015"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2015-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2015-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(gof_behaviour)</span></code></pre></div>
<p><img src="Chapter15_Integrated_Network_Science_Rtutorial_coevolution_networks_behaviors_siena_files/figure-html/unnamed-chunk-90-1.png" width="672" /></p>
</div>
<div id="time-heterogeneity" class="section level3 hasAnchor" number="15.7.2">
<h3><span class="header-section-number">15.7.2</span> Time Heterogeneity<a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#time-heterogeneity" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Finally, when we have more than two time periods, it is important to test for time heterogeneity, asking if the estimates are different from T1 to T2 compared to T2 and T3 (in the case of three waves). Let's test whether the estimates differ from T1 to T2 vs. T2 to T3 using the <code>sienaTimeTest()</code> function. The input is the estimated model.</p>
<div class="sourceCode" id="cb2016"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2016-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2016-1" aria-hidden="true" tabindex="-1"></a>timetest <span class="ot">&lt;-</span> <span class="fu">sienaTimeTest</span>(mod1_3wave_example)</span></code></pre></div>
<div class="sourceCode" id="cb2017"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2017-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2017-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(timetest) </span></code></pre></div>
<pre><code>## Joint significance test of time heterogeneity:
## chi-squared =  10.25, d.f. = 10, p= 0.4185, 
## where H0: The following parameters are zero:
##  ( 1) (*)Dummy2:outdegree (density)
##  ( 2) (*)Dummy2:reciprocity
##  ( 3) (*)Dummy2:transitive triplets
##  ( 4) (*)Dummy2:alcohol_depvar alter
##  ( 5) (*)Dummy2:alcohol_depvar ego
##  ( 6) (*)Dummy2:alcohol_depvar similarity
##  ( 7) (*)Dummy2:alcohol_depvar linear shape
##  ( 8) (*)Dummy2:alcohol_depvar quadratic shape
##  ( 9) (*)Dummy2:alcohol_depvar average similarity
##  (10) (*)Dummy2:alcohol_depvar: effect from gender
## 
## Individual significance tests and one-step estimators:
##                                              Initial Est. One Step Est. p-Value
## outdegree (density)                          -2.5172      -2.4831        0.0000
## reciprocity                                   2.0224       1.9256        0.0000
## transitive triplets                           0.5646       0.5222        0.0000
## alcohol_depvar alter                         -0.0407      -0.0021        0.5060
## alcohol_depvar ego                            0.0349      -0.0385        0.5920
## alcohol_depvar similarity                     0.7936       0.7868        0.0270
## alcohol_depvar linear shape                   0.4561       0.4929        0.0020
## alcohol_depvar quadratic shape                0.0623       0.1869        0.5320
## alcohol_depvar average similarity             7.1645       8.8445        0.0010
## alcohol_depvar: effect from gender            0.0497      -0.0320        0.8050
## (*)Dummy2:outdegree (density)                 0.0000      -0.0936        0.1250
## (*)Dummy2:reciprocity                         0.0000       0.1965        0.0200
## (*)Dummy2:transitive triplets                 0.0000       0.1061        0.0080
## (*)Dummy2:alcohol_depvar alter                0.0000      -0.0836        0.8830
## (*)Dummy2:alcohol_depvar ego                  0.0000       0.1449        0.3850
## (*)Dummy2:alcohol_depvar similarity           0.0000      -0.0245        0.7640
## (*)Dummy2:alcohol_depvar linear shape         0.0000       0.0097        0.9560
## (*)Dummy2:alcohol_depvar quadratic shape      0.0000      -0.2384        0.4400
## (*)Dummy2:alcohol_depvar average similarity   0.0000      -2.8301        0.9200
## (*)Dummy2:alcohol_depvar: effect from gender  0.0000       0.0721        0.9670
## 
## Effect-wise joint significance tests
## (i.e. each effect across all dummies):
##                                    chi-sq. df p-value
## outdegree (density)                   2.36  1   0.124
## reciprocity                           5.41  1   0.020
## transitive triplets                   7.07  1   0.008
## alcohol_depvar alter                  0.02  1   0.888
## alcohol_depvar ego                    0.75  1   0.386
## alcohol_depvar similarity             0.09  1   0.764
## alcohol_depvar linear shape           0.00  1   1.000
## alcohol_depvar quadratic shape        0.60  1   0.439
## alcohol_depvar average similarity     0.01  1   0.920
## alcohol_depvar: effect from gender    0.00  1   1.000
## 
## Period-wise joint significance tests
## (i.e. each period across all parameters):
##          chi-sq. df p-value
## Period 1   10.25 10   0.419
## Period 2   10.25 10   0.419
## 
## Use the following indices for plotting:
##   (1) outdegree (density)
##   (2) reciprocity
##   (3) transitive triplets
##   (4) alcohol_depvar alter
##   (5) alcohol_depvar ego
##   (6) alcohol_depvar similarity
##   (7) alcohol_depvar linear shape
##   (8) alcohol_depvar quadratic shape
##   (9) alcohol_depvar average similarity
##   (10) alcohol_depvar: effect from gender
## 
## If you would like to fit time dummies to your model,
## use the includeTimeDummy function.
## Type &quot;?sienaTimeTest&quot; for more information on this output.</code></pre>
<p>The main test we are interested in is the 'joint significance' test. The null hypothesis is that the effects are the same across the waves. A p value &lt; .05 would offer evidence to reject that null (meaning the effects may differ across waves). Here there is not strong evidence of time differences. If we had found significant differences we may want to include terms that allow the coefficients (at least some of them) to vary by time. In particular, we would want to look at the significance tests on the specific coefficients interacted with time; here we would focus on the series of coefficients starting with 'Dummy 2', looking at which cases there is a significant t-test (suggesting that the coefficient for T2 - T3, for example, is different than the coefficient in T1 - T2). We would then use an <code>includeTimeDummy()</code> function to include the desired terms, allowing those coefficients to vary across time. For example, let's run through a quick example where we allow the coefficients on density and transitive triplets to vary between the first period of change (T1 to T2) and the second (T2 to T3).</p>
<div class="sourceCode" id="cb2019"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2019-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2019-1" aria-hidden="true" tabindex="-1"></a>siena_effects_3wave_example <span class="ot">&lt;-</span> <span class="fu">includeTimeDummy</span>(siena_effects_3wave_example, </span>
<span id="cb2019-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2019-2" aria-hidden="true" tabindex="-1"></a>                                                density, </span>
<span id="cb2019-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2019-3" aria-hidden="true" tabindex="-1"></a>                                                transTrip, </span>
<span id="cb2019-4"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2019-4" aria-hidden="true" tabindex="-1"></a>                                                <span class="at">timeDummy =</span> <span class="st">&quot;2&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb2020"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2020-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2020-1" aria-hidden="true" tabindex="-1"></a>siena_effects_3wave_example</span></code></pre></div>
<pre><code>##    name           effectName                          include fix   test  initialValue parm timeDummy
## 1  friendship     constant friendship rate (period 1) TRUE    FALSE FALSE    7.41692   0    ,        
## 2  friendship     constant friendship rate (period 2) TRUE    FALSE FALSE    6.16651   0    ,        
## 3  friendship     outdegree (density)                 TRUE    FALSE FALSE   -1.66821   0    2        
## 4  friendship     reciprocity                         TRUE    FALSE FALSE    0.00000   0    ,        
## 5  friendship     transitive triplets                 TRUE    FALSE FALSE    0.00000   0    2        
## 6  friendship     alcohol_depvar alter                TRUE    FALSE FALSE    0.00000   0    ,        
## 7  friendship     alcohol_depvar ego                  TRUE    FALSE FALSE    0.00000   0    ,        
## 8  friendship     alcohol_depvar similarity           TRUE    FALSE FALSE    0.00000   0    ,        
## 9  alcohol_depvar rate alcohol_depvar (period 1)      TRUE    FALSE FALSE    0.76577   0    ,        
## 10 alcohol_depvar rate alcohol_depvar (period 2)      TRUE    FALSE FALSE    1.15233   0    ,        
## 11 alcohol_depvar alcohol_depvar linear shape         TRUE    FALSE FALSE    0.35525   0    ,        
## 12 alcohol_depvar alcohol_depvar quadratic shape      TRUE    FALSE FALSE    0.00000   0    ,        
## 13 alcohol_depvar alcohol_depvar average similarity   TRUE    FALSE FALSE    0.00000   0    ,        
## 14 alcohol_depvar alcohol_depvar: effect from gender  TRUE    FALSE FALSE    0.00000   0    ,</code></pre>
<p>Note that we now have a timeDummy column and we see a 2 in the density and transitive triplets rows. Now let's run the model and take a look at the results.</p>
<div class="sourceCode" id="cb2022"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2022-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2022-1" aria-hidden="true" tabindex="-1"></a>mod2_3wave_example <span class="ot">&lt;-</span> <span class="fu">siena07</span>(input_options_3wave,</span>
<span id="cb2022-2"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2022-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">data =</span> friend_behavior_covar,</span>
<span id="cb2022-3"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2022-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">effects =</span> siena_effects_3wave_example, </span>
<span id="cb2022-4"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2022-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">returnDeps =</span> <span class="cn">TRUE</span>, </span>
<span id="cb2022-5"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2022-5" aria-hidden="true" tabindex="-1"></a>                              <span class="at">initC =</span> <span class="cn">TRUE</span>, <span class="at">useCluster =</span> <span class="cn">TRUE</span>, </span>
<span id="cb2022-6"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2022-6" aria-hidden="true" tabindex="-1"></a>                              <span class="at">nbrNodes =</span> <span class="dv">2</span>) </span></code></pre></div>
<div class="sourceCode" id="cb2023"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2023-1"><a href="ch15-coevolution-networks-behaviors-siena-saom-R.html#cb2023-1" aria-hidden="true" tabindex="-1"></a>mod2_3wave_example</span></code></pre></div>
<pre><code>## Estimates, standard errors and convergence t-ratios
## 
##                                                        Estimate   Standard   Convergence 
##                                                                     Error      t-ratio   
## Network Dynamics 
##    1. rate constant friendship rate (period 1)         14.6715  ( 1.4518   )    0.0103   
##    2. rate constant friendship rate (period 2)         11.9149  ( 1.0703   )    0.0100   
##    3. eval outdegree (density)                         -2.5164  ( 0.0498   )   -0.0219   
##    4. eval reciprocity                                  2.0263  ( 0.0954   )   -0.0207   
##    5. eval transitive triplets                          0.5675  ( 0.0234   )   -0.0120   
##    6. eval alcohol_depvar alter                        -0.0378  ( 0.0542   )   -0.0039   
##    7. eval alcohol_depvar ego                           0.0168  ( 0.0674   )    0.0219   
##    8. eval alcohol_depvar similarity                    0.7463  ( 0.3329   )    0.0177   
##    9. eval Dummy2:friendship ego x transitive triplets  0.1116  ( 0.0448   )    0.0598   
##   10. eval Dummy2:friendship ego                       -0.0240  ( 0.0846   )    0.0541   
## 
## Behavior Dynamics
##   11. rate rate alcohol_depvar (period 1)               1.6302  ( 0.3225   )   -0.0225   
##   12. rate rate alcohol_depvar (period 2)               2.7327  ( 0.5251   )   -0.0555   
##   13. eval alcohol_depvar linear shape                  0.4639  ( 0.1310   )   -0.0091   
##   14. eval alcohol_depvar quadratic shape               0.0641  ( 0.0984   )    0.0054   
##   15. eval alcohol_depvar average similarity            7.2544  ( 2.1290   )    0.0079   
##   16. eval alcohol_depvar: effect from gender           0.0576  ( 0.1965   )   -0.0018   
## 
## Overall maximum convergence ratio:    0.1001 
## 
## 
## Degrees constrained to maximum values:
## friendship : 6 
## 
## 
## Total of 5129 iteration steps.</code></pre>
<p>We see that there are now interactions between time and two terms (density and transitive triplets). These two are labeled as 'friendship ego' and 'friendship ego X transitive triplets'. For example, we can see that there is some evidence that the effect of transitivity is higher in later time periods than in earlier ones.</p>
<p>Overall, this tutorial has offered two examples of running SIENA models in R. We have covered only a portion of the full range of applications that the <strong>RSiena</strong> package can handle. For example, it is possible to use the SIENA framework to do dynamic simulations (in an analogous fashion as we saw in <a href="ch13-Longitudinal-Network-Models-STERGM-R.html#ch13-Longitudinal-Network-Models-STERGM-R">Chapter 13</a>), making it possible to explore hypothetical scenarios and test theories related to the coevolution of networks and behaviors. See <a href="http://www.stats.ox.ac.uk/~snijders/siena/" class="uri">http://www.stats.ox.ac.uk/~snijders/siena/</a> for many helpful scripts and tutorials.</p>
<p>This serves as the final tutorial for the book. Throughout the tutorials, we have included in-depth analyses of different network topics and models. Of course, a single book cannot hope to cover everything a researcher may want to do, and we encourage readers to explore the packages discussed in this book more thoroughly with their own data and project in mind.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ch14-Network-Diffusion-Social-Processes-R.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="how-to-cite.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo"]
},
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 2.5
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"info": false
});
});
</script>

</body>

</html>
